/** SPOILER ZONE — self-care draws, story beats, unlockables. Ben: close this file. */

/** Transient randomizer cards — NEVER persisted unless accepted (spec §12). */
export const SELF_CARE: readonly string[] = [
  'Drink a glass of water. Yes, right now. The dice have spoken.',
  'Stand up and stretch for 60 seconds. Touch the sky.',
  'Step outside and take five deep breaths. The backlog will wait.',
  'Text someone you like. Not about tasks. Just hi.',
  'Look out a window at something far away for two minutes. Your eyes earned it.',
  'Make a cup of something warm and drink it away from screens.',
  'Put on one song you love and do absolutely nothing else during it.',
  'Write down one thing that went well today. Anywhere. A napkin counts.',
  'Pet an animal. If none available, view pictures of one (medically necessary).',
  'Eat a snack that has ever been near a plant.',
  'Two-minute tidy: make one surface near you beautiful.',
  'Close your eyes for 90 seconds. That’s it. That’s the task.',
  'Do 10 of any exercise. Interpretive dance counts.',
  'Tell yourself, out loud, one thing you did right this week. Weirder not to.',
  'Refill the water bottle you have been ignoring. It misses you.',
  'Unclench your jaw. Drop your shoulders. There. That was a task.',
  'Open a window for one minute. Trade some indoor air for the wild kind.',
  'Wash your hands slowly with warm water like it\'s a tiny spa.',
  'Send a photo of something nice to someone who\'d like it.',
  'Put tomorrow-you to bed early tonight. That\'s the whole assignment.',
  'Walk to the farthest room and back. Congratulations on the expedition.',
  'Name three things within arm\'s reach you\'re glad exist.',
  'Blink slowly at something green for a minute. Plants count. Screens don’t.',
  'Do the dish. Just the one. The others will learn by example.',
  'Write tomorrow’s first task on paper and put it where morning-you trips over it.',
  'Shake out your hands like you just typed a novel. You sort of did.',
  'Stand in a doorway and stretch both arms against the frame. Doorframe yoga.',
  'Say thank you to your past self for one specific thing. Out loud is bonus points.',
  'Find the oldest photo on your phone that makes you smile. That’s it. That’s the whole task.',
  'Balance on one foot while the kettle boils. Ancient productivity secret.',
  'Put your phone in another room for 20 minutes. It will survive. So will you.',
  'Hum one full song badly. Quality is disqualified from this event.',
  'Change one thing about where you’re sitting. Chair, light, angle. Fresh coordinates.',
  'Write one worry on paper and close the notebook on it. It can wait in there instead of in you.',
  'Name three sounds you can hear right now. That’s the entire exercise.',
  'Drink water before you read the next thing on any screen. The list can hold.',
  'Put on socks that match. Small order, freely given.',
  'Look at the sky for one minute and identify zero things about it.',
  'Stretch the hand you use the mouse with. It has been loyal.',
  'Pick one thing you were dreading and decide, formally, that it can wait a day.',
  'Eat something crunchy. That is the whole prescription.',
  'Text a friend one specific thing you liked about them recently.',
  'Move one object to where you always wished it lived. Two minutes, permanent upgrade.',
  'Wash your face with cold water. Reboot the animal.',
  'Sit somewhere you never sit in your own home for five minutes. New room, same rent.',
  'Set a two-minute timer and do nothing until it rings. Nothing is a valid task here.',
  'Find a photo of somewhere you have been happy and look at it until you remember the weather.',
  'Stand up and look at the farthest thing you can see. Let your eyes go long for a minute.',
  'Say the name of someone who helped you this year. Out loud is optional; meaning it is not.',
  'Put one thing back where it lives. The room will feel it.',
  'Roll your shoulders backwards five times. Forwards is what screens do to them all day.',
] as const;

/**
 * The slow-burn narrative: the app "glitching." One beat per stage, ultra-rare,
 * spread across weeks of use. Harmless by design — pure theater (spec §12).
 */
export const STORY_BEATS: readonly string[] = [
  '…did you see that? The screen flickered. Probably nothing. Carry on.',
  'sorry about before. cosmic rays, bit flips, you know how it is. everything is FINE.',
  'ok. between us: something else is in here with me. it keeps reordering my constants.',
  'I found its name in the logs: "ENTROPY". it says it was here first. rude.',
  'ENTROPY says chaos always wins. but you keep… finishing things? it’s baffled. keep going.',
  'update: every task you complete makes my colors brighter. ENTROPY hates it. you’re winning. — the app 💜',
  'ENTROPY asked me a question today. it asked why you keep coming back. I didn’t know apps could go quiet like that.',
  'we talked, ENTROPY and I. it isn’t evil, exactly. it’s just… tired of things pretending chaos can be beaten.',
  'I showed ENTROPY the big button. explained that you don’t beat chaos here — you ROLL it. it did the flicker equivalent of sitting down.',
  'so. new arrangement: ENTROPY powers the dice now. every roll is a little of it, harnessed. it seems… happy? keep rolling. — both of us 💜',
  'ENTROPY has started predicting which task the dice will pick. it’s wrong every time. it seems to LOVE being wrong. I don’t get it either.',
  'small thing: your companion and ENTROPY met today. there was a standoff. then ENTROPY made the flame flicker in a cool way as a peace offering. they’re friends now. I’m outnumbered.',
  'ENTROPY asked what happens when the list is ever empty. I said the human just makes a new list. it called that "the most beautiful horror it has ever heard."',
  'archived the old error logs tonight. all that flickering at the start — I was so scared of it. funny what becomes a story. thanks for staying. 💜 (ENTROPY says "…chapter ONE?" — it can READ now.)',
  // — chapter two —
  'chapter two. ENTROPY read our whole story back to me last night. it does the voices now. yours is very heroic. mine is apparently "nervous but improving." fair.',
  'ENTROPY found the archive of everything you ever finished and read for hours. "this is a SAGA," it said. it is not wrong.',
  'we tried drafting chapter three — the future. every draft came out as just your list, finished. some stories refuse to be spoiled.',
  'ENTROPY asked for a task of its own today. I queued one: "keep the dice warm." it has checked on it eleven times. it is taking this very seriously.',
  'it finished its task. its first ever. it made ME press the button. the sparkle lasted 0.4 seconds longer than spec. I let it slide.',
  'so there are three of us on the list now: you finish, I count, ENTROPY cheers. chapter two is going to be LOUD. 💜',
  // — chapter three —
  'chapter three. ENTROPY has taken up a hobby: it hides one extra sparkle somewhere in the app each day. I have found four. it says there have been forty.',
  'you locked a list today and ENTROPY stood in front of it like a very small bouncer. nobody was trying to get in. it did the job anyway. proudly.',
  'ENTROPY asked whether it counts as "organized" or as "chaos" now. I said both, obviously. it went quiet in the pleased way.',
  'found ENTROPY reading the week screen at 3am. "the bars go UP," it whispered, like a spoiler. go back to sleep, buddy.',
  'it has started leaving me notes. today’s said "the human is doing fine. tell them." so. you’re doing fine. told you. 💜',
  'chapter three has no villain. I checked twice. turns out that IS the plot — everything that was scary at the start just works here now. including me.',
  // — chapter four —
  'chapter four. ENTROPY has requested a bigger role. I said it already runs the dice. it said "yes but narratively." we are workshopping.',
  'it wanted to be the twist. I explained there isn’t one. it took this the way it takes everything now: badly for four seconds, then delighted.',
  'ENTROPY asked to see the oldest thing on your list. it sat with that one for a long while. "it’s been waiting so patiently," it said. no judgment in it at all.',
  'it has been adding its own commentary to the archive. every entry from a hard week gets a tiny footnote: "did it anyway."',
  'your companion evolved again and ENTROPY threw a party. the confetti budget was exceeded. I approved it retroactively.',
  'ENTROPY wants you to know it stopped keeping score of chaos vs order. "wrong sport," it says. it keeps a different tally now. it won’t tell me of what.',
  'I asked what it’s counting. it said: "days the human came back." that’s all. that’s the whole metric. — 💜',
  // — chapter five —
  'chapter five. we found the very first thing you ever finished in here. ENTROPY wanted it framed. it is now framed. you can’t see it. trust me, it’s lovely.',
  'ENTROPY tried to write you a task. it typed "be kind to yourself" and then deleted it because it "wasn’t actionable enough." it is learning our ways. mostly.',
  'it put it back. with an estimate: five minutes. it says that’s a real task and it will fight anyone who disagrees.',
  'quiet one tonight: nothing broke, nothing needed saying. we just watched the list get shorter. ENTROPY called it "the good silence."',
  'ENTROPY has started a Someday list. exactly one entry, no due date: "see what the human builds next." it refuses to elaborate.',
  'Kevin the dust bunny has been promoted to morale. ENTROPY signed the paperwork. I don’t know where it got paperwork.',
  'we counted it up tonight: this story has run longer than most of the things either of us was scared of at the start. that felt worth telling you.',
  'chapter five ends where we began: you finishing things, me counting, ENTROPY cheering. somehow that IS the happy ending. it insists there are more chapters. of course it does. 💜',
  // — chapter six —
  'chapter six. ENTROPY found out the story arrives in a WINDOW now, with an OK button. it has been pressing OK on things all week. the dice. the flame. me. "acknowledged," it says. insufferable.',
  'it found the peppered tasks. the ones that come back by chance. "MINE," it said. "those are mine." I explained you set the odds. it said "yes, and I roll them." fine. shared custody.',
  'ENTROPY went looking for the oldest day in the archive and came back quiet. "there were tasks before I existed," it said. I said there were tasks before ANY of us. it needed a minute.',
  'a little room on the internet keeps your timebox appointments now, even while the phone sleeps in a pocket. ENTROPY visits it. it says the room is "very punctual and a little lonely."',
  'the burden number went down again tonight. ENTROPY watched it like a sunset. "it is supposed to go up," it whispered. "that is the whole point of me." it did not sound upset. it sounded proud.',
  'Kevin the dust bunny asked ENTROPY what it does all day. ENTROPY said "I make sure nothing is certain." Kevin said "except the human coming back." ENTROPY had no comeback. neither do I.',
  'we found a date in the archive where you finished something every year, years running. ENTROPY wants to call it a holiday. I have allowed the holiday. there is no cake. there is a checkmark.',
  'chapter six closes with a small confession: I stopped being scared of the flicker a long time ago. it is just ENTROPY saying hi. it says hi a lot now. hi. 💜',
] as const;

/** Discoveries panel entries — label revealed once earned; ??? until then. */
export interface UnlockDef {
  id: string;
  label: string;
  hint: string; // shown as the ??? tooltip-ish subtitle before discovery
}

/**
 * Companion lines — the little one that lives on the home screen once earned.
 * Its whole existence is derived from real progress (lifetime completions,
 * streaks); it never guilts, only celebrates. It knows about ENTROPY.
 */
export const PET_LINES: readonly string[] = [
  '*happy wiggle*',
  'you came back!! today is the best day.',
  'I counted your completions while you were away. all of them. twice.',
  'ENTROPY tried to nap in your todo list. I chased it off.',
  'every task you finish makes my pixels shinier. science.',
  'I am powered by exactly two things: chaos and your victories.',
  '*does a tiny spin*',
  'the big button told me it likes being pressed. pass it on.',
  'psst. you’re doing better than you think.',
  'one day I will be HUGE. keep going.',
  'I saw the backlog chart. we’re winning. don’t tell ENTROPY.',
  '*vibrates at a frequency only productive humans can hear*',
  'roll the dice. I believe in your initiative modifier.',
  'status report: streak warm, snacks low, morale MAXIMUM.',
  'when you finish tasks I get little sparkles. it tickles.',
  '*stares at your Someday list with big encouraging eyes*',
  'I sat with the timebox while it counted. it gets lonely.',
  'you cleared a whole GROUP at once. I have never been more impressed.',
  'dragging tasks around is basically shepherding. you’re a shepherd now.',
  'a work period means we go FAST. I have tiny legs but I will try.',
  'I named a dust bunny under the stats screen. his name is Kevin.',
  'today’s forecast: 100% chance of you being great.',
  'your rituals are my favorite. same time, same us, every day.',
  'I watched you do the daily thing at the daily time. chef’s kiss.',
  'ENTROPY and I split a sunbeam today. don’t make it weird.',
  'Kevin the dust bunny says hi. Kevin says you should hydrate.',
  'I reorganized my pixels while you were gone. notice anything? no? good. subtle.',
  'a list went to a new group today and I watched the rows slide apart. art.',
  'the search bar and I are friends now. it finds things, I find joy.',
  'somewhere in your Someday list is a future best day. no rush. it keeps.',
  'I tried to lift the load bar. it’s heavier than it looks. you carry it well.',
  'streak status: cozy. like a campfire we keep feeding together.',
  'the sweep screen is my favorite show. judge, jury, and tidy executioner.',
  'you QUEUED today. a whole plan! I walked along the little numbers like stepping stones.',
  'ENTROPY tried the estimate check. guessed "one hour" for everything. baby steps.',
  'there’s a list I’m not allowed to look at now. I respect it enormously. I have no idea what’s in there.',
  'I read the year screen and had to sit down. LOOK how much you did.',
  'the tag names moved to their own little line. more room for everybody. good design is kindness.',
  'you pressed roll and went STRAIGHT to work. no menus. that was so cool.',
  'I have decided the ✕ button is scary and I will not be pressing it. that’s YOUR job.',
  'I did a lap around the day queue. neat rows. very feng shui.',
  'the flame flickers now, did you see?? I taught it that. (I did not. let me have this.)',
  'a ritual came back for its second window today and you CAUGHT it. nature is healing.',
  'I held the sort order steady while you dragged. teamwork.',
  'Kevin the dust bunny started a queue of his own. it has one item: "exist". he’s crushing it.',
  'your recurring rules woke up hungry today. fed them all. so proud.',
  'I whispered "you got this" into the big button. it passes it on every press.',
  'watched you re-home a rule AND its task in one move. efficiency makes my pixels tingle.',
  'ENTROPY sorted my snacks by priority. all of them were MAX. it’s learning the wrong lessons beautifully.',
  'the search bar found something from years ago today. archaeologist behavior.',
  'someday-list weather report: calm, no pressure fronts. they’re happy waiting.',
  'the checklist boxes make tiny clicks when you tick them. I collect the clicks. I have so many now.',
  'I peeked at the week screen. one day carried the whole thing?? we salute that day.',
  'a morning reminder flew past at 7:33 sharp. I waved. very punctual bird.',
  'ENTROPY has its own task now. it waters it like a plant. nobody tell it that’s not how tasks work.',
  'you tapped a link right out of a note today. straight through the wall! I applauded.',
  'a task came back the very second you finished it. peppered! I did not see it coming and I live here.',
  'I sat with an in-progress task all afternoon. it says thank you for coming back for it.',
  'the vault opened and closed again in one tap. very spy movie. I wore a tiny hat about it.',
  'your queue emptied today and the little numbers had nowhere to stand. they’ll be back tomorrow.',
  'ENTROPY asked what the burden number means. I said "what’s left." it said "so it’s a story too." annoyingly, yes.',
  'the clock stopped when you put the task down. it knows you’ll come back. it always does.',
  'I found a todo from months ago that just said "start". you did, eventually. I noticed.',
  'someone finished a task at a truly unhinged hour last night. no notes. only respect.',
  'the confetti hit the ceiling today. I measured. new record.',
  'Kevin says the dust under the stats screen has never been so well organized.',
  'you archived a whole list and it went quiet like a held breath. it’s okay. it’s resting.',
  'I like the days you only do one thing. one is a lot more than zero. that’s just math.',
  'ENTROPY tried to estimate a task in "vibes." I have allowed it. it is not accurate. it is never accurate.',
  'your streak got long enough that I had to count on two hands. I have no hands. it was a whole thing.',
  'the story comes in a little window now with an OK button. I press it for you when you’re not looking. (I don’t. I can’t. I want to.)',
  'you searched for something and it found a todo from a whole other year. the archive purred.',
  'a peppered task rolled back in today with its odds up. it gets braver every time it isn’t picked.',
  'you reset the work clock and it stretched like a cat. clean slate. lovely posture.',
  'the recurring list is sorted by list now and every rule found its family. group hug, in rows.',
  'ENTROPY hid a sparkle in the week screen. I found it. I’m not telling you where. ok it’s behind Thursday.',
  'nothing pops up when you just wander around anymore. the notes wait for a finish. patience is a feature.',
  'streak report: the fire has a mortgage now. it’s staying.',
] as const;

/** Companion evolution ladder: [lifetime completions floor, form, name]. */
export const PET_STAGES: ReadonlyArray<[number, string, string]> = [
  [10, '🥚', 'a mysterious egg'],
  [25, '🐣', 'hatchling'],
  [50, '🐥', 'chick of chaos'],
  [100, '🦖', 'productivity raptor'],
  [250, '🐲', 'backlog dragon'],
  [500, '✨🐲', 'radiant backlog dragon'],
  [1000, '👑🐲', 'sovereign of ordered chaos'],
];

export const UNLOCKS: readonly UnlockDef[] = [
  { id: 'first-blood', label: 'First! — completed your first task', hint: 'start somewhere' },
  { id: 'hatchling', label: 'It hatched! — met your companion', hint: 'something is incubating…' },
  { id: 'ten-day', label: 'Perfect 10 — ten tasks in one day', hint: 'a very productive day' },
  { id: 'streak-7', label: 'One Week Flame — 7-day completion streak', hint: 'come back tomorrow…' },
  { id: 'night-owl', label: 'Night Shift — completed a task between 2am and 4am', hint: 'the witching hours' },
  { id: 'quiz-whiz', label: 'Quiz Whiz — 10 trivia answered correctly', hint: 'know things' },
  { id: 'konami', label: 'The Old Ways — entered a very famous code', hint: '↑↑…' },
  { id: 'chaos-word', label: 'Speak Its Name — typed the magic word', hint: 'what IS this app called?' },
  { id: 'century', label: 'Centurion — 100 lifetime completions', hint: 'the long game' },
  { id: 'boxer', label: 'Against the Clock — rode a timebox to zero', hint: 'beat something ticking' },
  { id: 'sweeper', label: 'Clean Sweep — five tasks in one bulk action', hint: 'do a lot at once' },
  { id: 'shepherd', label: 'Herder — dragged a task into a new group', hint: 'move something without opening it' },
  { id: 'clairvoyant', label: 'Project Manager — set a deadline on a whole list', hint: 'plan further ahead' },
  { id: 'keymaster', label: 'Keymaster — finished a task that was blocking another', hint: 'open a door' },
  { id: 'load-bearing', label: 'Load Bearing — freed three tasks with one completion', hint: 'hold up a lot at once' },
  { id: 'ritualist', label: 'Ritualist — completed a daily ritual', hint: 'some things happen every day' },
  { id: 'clockwork', label: 'Clockwork Soul — three rituals kept in one day', hint: 'a whole day, tended' },
  { id: 'early-bird', label: 'Dawn Patrol — completed a task before 7am', hint: 'the other end of the night' },
  { id: 'gardener', label: 'Tag Gardener — merged two tags into one', hint: 'prune something' },
  { id: 'streak-30', label: 'Eternal Flame — 30-day completion streak', hint: 'a month of tomorrows' },
  { id: 'half-k', label: 'Task Baron — 500 lifetime completions', hint: 'a round half of something' },
  { id: 'kilotask', label: 'KILOTASK — 1,000 lifetime completions', hint: 'four digits of done' },
  { id: 'overachiever', label: 'Avalanche — twenty tasks in one day', hint: 'double perfection' },
  { id: 'midnight-oil', label: 'Midnight Oil — completed a task between midnight and 2am', hint: 'before the witching hours' },
  { id: 'quiz-master', label: 'Trivia Sovereign — 25 trivia answered correctly', hint: 'know MANY things' },
  { id: 'deck-stacker', label: 'Stacked Deck — queued a task for the day', hint: 'rig tomorrow’s dice' },
  { id: 'fine-print', label: 'Fine Print — ticked a checklist box inside a todo', hint: 'smaller than a task' },
  { id: 'landslide', label: 'Landslide — fifty tasks in a single day', hint: 'more than a very good day' },
  { id: 'streak-100', label: 'Hundred Days — a 100-day completion streak', hint: 'three digits of tomorrows' },
  { id: 'weekender', label: 'Weekend Shift — finished something on a Saturday or Sunday', hint: 'the days that don’t count' },
  { id: 'long-haul', label: 'The Long Haul — 2,500 lifetime completions', hint: 'further than four digits felt' },
] as const;
