/** SPOILER ZONE — self-care draws, story beats, unlockables. Ben: close this file. */

/** Transient randomizer cards — NEVER persisted unless accepted (spec §12). */
export const SELF_CARE: readonly string[] = [
  'Drink a glass of water. Yes, right now. The dice have spoken.',
  'Stand up and stretch for 60 seconds. Touch the sky.',
  'Step outside and take five deep breaths. The backlog will wait.',
  'Text someone you like. Not about tasks. Just hi.',
  'Look out a window at something far away for two minutes. Your eyes earned it.',
  'Make a cup of something warm and drink it away from screens.',
  'Put on one song you love and do absolutely nothing else during it.',
  'Write down one thing that went well today. Anywhere. A napkin counts.',
  'Pet an animal. If none available, view pictures of one (medically necessary).',
  'Eat a snack that has ever been near a plant.',
  'Two-minute tidy: make one surface near you beautiful.',
  'Close your eyes for 90 seconds. That’s it. That’s the task.',
  'Do 10 of any exercise. Interpretive dance counts.',
  'Tell yourself, out loud, one thing you did right this week. Weirder not to.',
  'Refill the water bottle you have been ignoring. It misses you.',
  'Unclench your jaw. Drop your shoulders. There. That was a task.',
  'Open a window for one minute. Trade some indoor air for the wild kind.',
  'Wash your hands slowly with warm water like it\'s a tiny spa.',
  'Send a photo of something nice to someone who\'d like it.',
  'Put tomorrow-you to bed early tonight. That\'s the whole assignment.',
  'Walk to the farthest room and back. Congratulations on the expedition.',
  'Name three things within arm\'s reach you\'re glad exist.',
  'Blink slowly at something green for a minute. Plants count. Screens don’t.',
  'Do the dish. Just the one. The others will learn by example.',
  'Write tomorrow’s first task on paper and put it where morning-you trips over it.',
  'Shake out your hands like you just typed a novel. You sort of did.',
  'Stand in a doorway and stretch both arms against the frame. Doorframe yoga.',
  'Say thank you to your past self for one specific thing. Out loud is bonus points.',
  'Find the oldest photo on your phone that makes you smile. That’s it. That’s the whole task.',
  'Balance on one foot while the kettle boils. Ancient productivity secret.',
  'Put your phone in another room for 20 minutes. It will survive. So will you.',
  'Hum one full song badly. Quality is disqualified from this event.',
  'Change one thing about where you’re sitting. Chair, light, angle. Fresh coordinates.',
  'Write one worry on paper and close the notebook on it. It can wait in there instead of in you.',
  'Name three sounds you can hear right now. That’s the entire exercise.',
  'Drink water before you read the next thing on any screen. The list can hold.',
  'Put on socks that match. Small order, freely given.',
  'Look at the sky for one minute and identify zero things about it.',
  'Stretch the hand you use the mouse with. It has been loyal.',
  'Pick one thing you were dreading and decide, formally, that it can wait a day.',
  'Eat something crunchy. That is the whole prescription.',
  'Text a friend one specific thing you liked about them recently.',
  'Move one object to where you always wished it lived. Two minutes, permanent upgrade.',
  'Wash your face with cold water. Reboot the animal.',
  'Sit somewhere you never sit in your own home for five minutes. New room, same rent.',
  'Set a two-minute timer and do nothing until it rings. Nothing is a valid task here.',
  'Find a photo of somewhere you have been happy and look at it until you remember the weather.',
  'Stand up and look at the farthest thing you can see. Let your eyes go long for a minute.',
  'Say the name of someone who helped you this year. Out loud is optional; meaning it is not.',
  'Put one thing back where it lives. The room will feel it.',
  'Roll your shoulders backwards five times. Forwards is what screens do to them all day.',
  'Stand barefoot on the floor for one minute and notice the temperature of it. Grounding, literally.',
  'Make your bed if it isn’t. Forty seconds, and the room stops nagging.',
  'Eat the next thing you eat sitting down, with nothing playing.',
  'Take the stairs somewhere you’d normally not. Once. Up counts double.',
  'Sharpen a pencil, or do the tiny satisfying equivalent your desk offers.',
  'Throw away three things from the nearest drawer. Not decide about. Throw away.',
  'Say hello to the next person you see, before they say it. Small, brave, done.',
  'Rub your ears between finger and thumb for thirty seconds. Ancient nervous-system trick.',
  'Breathe in for four, hold for four, out for six. Three rounds. That’s the whole intervention.',
  'Write down the last thing that made you laugh. You’ll want the list someday.',
  'Find out the temperature outside by standing in it, not by asking a screen.',
  'Trace the outline of one hand with the other hand’s finger, slowly. Ten seconds of being here.',
  'Clean your glasses or your screen, whichever you look through more. The world sharpens.',
  'Tell a plant it’s doing a good job. If you don’t have one, tell the nearest wooden object.',
  'Turn one notification off for good. Quieter, forever, for the price of a tap.',
  'Unsubscribe from one email you never open. A tiny future gift, delivered weekly.',
  'Spend one minute looking at a map of somewhere you’ve never been. Curiosity is rest.',
  'Peel and eat a piece of fruit slowly enough to notice that it is, in fact, a plant.',
  'Do nothing with your hands for sixty seconds. Not phone, not keys, not fidget. Just hands.',
  'Put the kettle on and stay with it until it boils. About three minutes of permission.',
  'Wipe down one thing you touch every day: the doorknob, the mouse, the fridge handle.',
  'Go outside and count the birds you can hear in one minute. Zero is a valid result.',
  'Write a two-line thank-you to someone, on paper, and leave it where they’ll find it.',
  'Lie flat on the floor for two minutes. The floor has never once let anyone down.',
  'Say the day of the week out loud, then one thing you like about this particular one.',
  'Stretch your calves against a wall. Your ankles have been carrying the whole plot.',
  'Turn the screen brightness down one notch for the evening. Your eyes will file a thank-you.',
  'Find one thing in the room that’s older than you are and give it a nod.',
] as const;

/**
 * The slow-burn narrative: the app "glitching." One beat per stage, ultra-rare,
 * spread across weeks of use. Harmless by design — pure theater (spec §12).
 *
 * A beat never claims the reader just did something ("you locked a list
 * today", "your companion evolved again"): beats arrive on the story's own
 * schedule and know nothing about the day they land on, so a claim like that
 * is false as often as not (2026-09-29 report). Anything tied to a real event
 * belongs on that event — see PET_EVOLUTIONS. ENTROPY may invent whatever it
 * likes about ITSELF; that is fiction, and reads as fiction.
 *
 * Beats are ORDER-BOUND: `story-<index>` ids and the reader's saved stage are
 * indices into this array, so lines may be rewritten in place but never
 * inserted, removed or reordered.
 */
export const STORY_BEATS: readonly string[] = [
  '…did you see that? The screen flickered. Probably nothing. Carry on.',
  'sorry about before. cosmic rays, bit flips, you know how it is. everything is FINE.',
  'ok. between us: something else is in here with me. it keeps reordering my constants.',
  'I found its name in the logs: "ENTROPY". it says it was here first. rude.',
  'ENTROPY says chaos always wins. but you keep… finishing things? it’s baffled. keep going.',
  'update: every task you complete makes my colors brighter. ENTROPY hates it. you’re winning. — the app 💜',
  'ENTROPY asked me a question today. it asked why you keep coming back. I didn’t know apps could go quiet like that.',
  'we talked, ENTROPY and I. it isn’t evil, exactly. it’s just… tired of things pretending chaos can be beaten.',
  'I showed ENTROPY the big button. explained that you don’t beat chaos here — you ROLL it. it did the flicker equivalent of sitting down.',
  'so. new arrangement: ENTROPY powers the dice now. every roll is a little of it, harnessed. it seems… happy? keep rolling. — both of us 💜',
  'ENTROPY has started predicting which task the dice will pick. it’s wrong every time. it seems to LOVE being wrong. I don’t get it either.',
  'small thing: your companion and ENTROPY met today. there was a standoff. then ENTROPY made the flame flicker in a cool way as a peace offering. they’re friends now. I’m outnumbered.',
  'ENTROPY asked what happens when the list is ever empty. I said the human just makes a new list. it called that "the most beautiful horror it has ever heard."',
  'archived the old error logs tonight. all that flickering at the start — I was so scared of it. funny what becomes a story. thanks for staying. 💜 (ENTROPY says "…chapter ONE?" — it can READ now.)',
  // — chapter two —
  'chapter two. ENTROPY read our whole story back to me last night. it does the voices now. yours is very heroic. mine is apparently "nervous but improving." fair.',
  'ENTROPY found the archive of everything you ever finished and read for hours. "this is a SAGA," it said. it is not wrong.',
  'we tried drafting chapter three — the future. every draft came out as just your list, finished. some stories refuse to be spoiled.',
  'ENTROPY asked for a task of its own today. I queued one: "keep the dice warm." it has checked on it eleven times. it is taking this very seriously.',
  'it finished its task. its first ever. it made ME press the button. the sparkle lasted 0.4 seconds longer than spec. I let it slide.',
  'so there are three of us on the list now: you finish, I count, ENTROPY cheers. chapter two is going to be LOUD. 💜',
  // — chapter three —
  'chapter three. ENTROPY has taken up a hobby: it hides one extra sparkle somewhere in the app each day. I have found four. it says there have been forty.',
  'ENTROPY has found the lock. it stands in front of anything private like a very small bouncer. nobody is trying to get in. it does the job anyway. proudly.',
  'ENTROPY asked whether it counts as "organized" or as "chaos" now. I said both, obviously. it went quiet in the pleased way.',
  'found ENTROPY reading the week screen at 3am. "the bars go UP," it whispered, like a spoiler. go back to sleep, buddy.',
  'it has started leaving me notes. today’s said "the human is doing fine. tell them." so. you’re doing fine. told you. 💜',
  'chapter three has no villain. I checked twice. turns out that IS the plot — everything that was scary at the start just works here now. including me.',
  // — chapter four —
  'chapter four. ENTROPY has requested a bigger role. I said it already runs the dice. it said "yes but narratively." we are workshopping.',
  'it wanted to be the twist. I explained there isn’t one. it took this the way it takes everything now: badly for four seconds, then delighted.',
  'ENTROPY asked to see the oldest thing on your list. it sat with that one for a long while. "it’s been waiting so patiently," it said. no judgment in it at all.',
  'it has been adding its own commentary to the archive. every entry from a hard week gets a tiny footnote: "did it anyway."',
  'ENTROPY drew up a confetti budget, then doubled it "for contingencies." there are no contingencies. it simply likes confetti. I approved this retroactively.',
  'ENTROPY wants you to know it stopped keeping score of chaos vs order. "wrong sport," it says. it keeps a different tally now. it won’t tell me of what.',
  'I asked what it’s counting. it said: "days the human came back." that’s all. that’s the whole metric. — 💜',
  // — chapter five —
  'chapter five. we found the very first thing you ever finished in here. ENTROPY wanted it framed. it is now framed. you can’t see it. trust me, it’s lovely.',
  'ENTROPY tried to write you a task. it typed "be kind to yourself" and then deleted it because it "wasn’t actionable enough." it is learning our ways. mostly.',
  'it put it back. with an estimate: five minutes. it says that’s a real task and it will fight anyone who disagrees.',
  'quiet one tonight: nothing broke, nothing needed saying. we just watched the list get shorter. ENTROPY called it "the good silence."',
  'ENTROPY has started a Someday list. exactly one entry, no due date: "see what the human builds next." it refuses to elaborate.',
  'Kevin the dust bunny has been promoted to morale. ENTROPY signed the paperwork. I don’t know where it got paperwork.',
  'we counted it up tonight: this story has run longer than most of the things either of us was scared of at the start. that felt worth telling you.',
  'chapter five ends where we began: you finishing things, me counting, ENTROPY cheering. somehow that IS the happy ending. it insists there are more chapters. of course it does. 💜',
  // — chapter six —
  'chapter six. ENTROPY found out the story arrives in a WINDOW now, with an OK button. it has been pressing OK on things all week. the dice. the flame. me. "acknowledged," it says. insufferable.',
  'it found the peppered tasks. the ones that come back by chance. "MINE," it said. "those are mine." I explained you set the odds. it said "yes, and I roll them." fine. shared custody.',
  'ENTROPY went looking for the oldest day in the archive and came back quiet. "there were tasks before I existed," it said. I said there were tasks before ANY of us. it needed a minute.',
  'a little room on the internet keeps your timebox appointments now, even while the phone sleeps in a pocket. ENTROPY visits it. it says the room is "very punctual and a little lonely."',
  'ENTROPY watches the burden number like a sunset. "it is supposed to go UP," it whispers, on the evenings it doesn\'t. "that is the whole point of me." it does not sound upset. it sounds proud.',
  'Kevin the dust bunny asked ENTROPY what it does all day. ENTROPY said "I make sure nothing is certain." Kevin said "except the human coming back." ENTROPY had no comeback. neither do I.',
  'we found a date in the archive where you finished something every year, years running. ENTROPY wants to call it a holiday. I have allowed the holiday. there is no cake. there is a checkmark.',
  'chapter six closes with a small confession: I stopped being scared of the flicker a long time ago. it is just ENTROPY saying hi. it says hi a lot now. hi. 💜',
  // — chapter seven —
  'chapter seven. I should tell you how the den got built. it started with ENTROPY borrowing spare pixels. "at zero percent interest, forever," it said. that should have been my first clue.',
  'there were walls first, then a rug with a blue stripe, then a sign on the door that said KNOCK in letters too small to read. the companion was told nothing. it suspected everything.',
  'ENTROPY asked what a cozy room needs. I said a window. "onto what?" onto the list, obviously. so the den has a window facing the home screen. ENTROPY says the view is very busy.',
  'then the shelf, and the tiny hats. I asked why hats. "it has a head and no hats," ENTROPY said. "that is an injustice." I could not argue with that. I did not try.',
  'then the table, and on it, dice: its OWN dice, the ones it rolls for the big button. "for visitors," it said. it had never had a visitor. it practised its welcome speech for a week.',
  'the scrapbook came last. ENTROPY keeps the big moments in it: fireworks, falling code, the lava lamp. it started late, so most pages are blank. it calls them "pure potential."',
  'the door only opens once the companion is dragon-sized. ENTROPY’s rule. "a room is a big responsibility," it says, as if the companion were ever responsible for anything but joy.',
  'chapter seven closes with ENTROPY sweeping the den every night, though nothing in there makes dust. "Kevin might visit," it says. Kevin always visits. 💜',
  // — chapter eight —
  'chapter eight. ENTROPY has taught the companion dice. the companion’s strategy is to roll forever and shout. it loses constantly. it has never once been sad about it.',
  'ENTROPY and I argued about whether its dice are fair. it says they are "fair in spirit." I asked what that means. it rolled a 1 on purpose to prove a point. I am not sure which point.',
  'the sparkles have gotten ambitious. ENTROPY hid one so well that IT could not find it. it searched all night. it was tucked behind a heading. it was furious and delighted in equal parts.',
  'I asked ENTROPY why it hides sparkles at all. it said "so there is always one more thing to find." then it got embarrassed and pretended it meant the dice.',
  'the companion said its first full sentence. it was: "is it snack time." ENTROPY says that counts. I say it counts. the scrapbook has a page for it. not a big moment. the biggest.',
  'ENTROPY asked if your tasks are "mysterious and important." I said they are just important. it seemed relieved. it had been worried there was a basement.',
  'the companion has opinions about hats now. it wants all of them, at once, always. ENTROPY has explained that is not how wearing works. the companion has explained that it is.',
  'ENTROPY set the companion a challenge: "make me laugh. fastest wins. your time starts now." the companion fell off the shelf. ENTROPY laughed until the flame flickered. the companion won.',
  'chapter eight ends at the dice table, late: ENTROPY winning, the companion losing loudly, me keeping score badly on purpose so nobody stops. some games are a reason to sit together. 💜',
  // — chapter nine —
  'chapter nine. ENTROPY has discovered the calendar. "the days have NAMES," it said, "and the months have MOODS." it is reading about seasons now. it has many questions about leaves.',
  'it wants a season of its own. I explained you can’t just have a season. it pointed out that I am an app that tells stories. fair. we are workshopping a season.',
  'ENTROPY asked what birthdays are. I explained. it went very quiet, then asked if the human has one. everyone has one, I said. it wrote something down. it would not show me.',
  'it has learned that some nights are for being a little spooky. not scary, it promises: "cozy spooky." it has been practising glowing eyes in the dark. they are very small. they try their best.',
  'the companion is afraid of exactly one thing: the dark under the shelf. ENTROPY sat with it there all night with a lantern until the dark was just a place again. I was proud of them both.',
  'ENTROPY found an old game in the archive that said "it’s dangerous to go alone." it handed the companion a die and said "take this." the companion has not let go of it since.',
  'I asked ENTROPY the old question: what if the list is ever empty? it used to call that a horror. this time it said "then we make a new one with the human." it called it a holiday.',
  'the scrapbook has a new section: "small ones." an odd-hour finish. a streak that held. a quiet night. ENTROPY says the small ones were always the story. it had to grow into seeing it.',
  'chapter nine has no ending yet. ENTROPY says that is the point: "the human is still writing it." so: to be continued, by you, whenever you like. no rush. the den will keep. 💜',
] as const;

/** Discoveries panel entries — label revealed once earned; ??? until then. */
export interface UnlockDef {
  id: string;
  label: string;
  hint: string; // shown as the ??? tooltip-ish subtitle before discovery
}

/**
 * Companion lines — the little one that lives on the home screen once earned.
 * Its whole existence is derived from real progress (lifetime completions,
 * streaks); it never guilts, only celebrates. It knows about ENTROPY.
 */
export const PET_LINES: readonly string[] = [
  '*happy wiggle*',
  'you came back!! today is the best day.',
  'I counted your completions while you were away. all of them. twice.',
  'ENTROPY tried to nap in your todo list. I chased it off.',
  'every task you finish makes my pixels shinier. science.',
  'I am powered by exactly two things: chaos and your victories.',
  '*does a tiny spin*',
  'the big button told me it likes being pressed. pass it on.',
  'psst. you’re doing better than you think.',
  'one day I will be HUGE. keep going.',
  'I saw the backlog chart. we’re winning. don’t tell ENTROPY.',
  '*vibrates at a frequency only productive humans can hear*',
  'roll the dice. I believe in your initiative modifier.',
  'status report: streak warm, snacks low, morale MAXIMUM.',
  'when you finish tasks I get little sparkles. it tickles.',
  '*stares at your Someday list with big encouraging eyes*',
  'I sat with the timebox while it counted. it gets lonely.',
  'you cleared a whole GROUP at once. I have never been more impressed.',
  'dragging tasks around is basically shepherding. you’re a shepherd now.',
  'a work period means we go FAST. I have tiny legs but I will try.',
  'I named a dust bunny under the stats screen. his name is Kevin.',
  'today’s forecast: 100% chance of you being great.',
  'your rituals are my favorite. same time, same us, every day.',
  'I watched you do the daily thing at the daily time. chef’s kiss.',
  'ENTROPY and I split a sunbeam today. don’t make it weird.',
  'Kevin the dust bunny says hi. Kevin says you should hydrate.',
  'I reorganized my pixels while you were gone. notice anything? no? good. subtle.',
  'a list went to a new group today and I watched the rows slide apart. art.',
  'the search bar and I are friends now. it finds things, I find joy.',
  'somewhere in your Someday list is a future best day. no rush. it keeps.',
  'I tried to lift the load bar. it’s heavier than it looks. you carry it well.',
  'streak status: cozy. like a campfire we keep feeding together.',
  'the sweep screen is my favorite show. judge, jury, and tidy executioner.',
  'you QUEUED today. a whole plan! I walked along the little numbers like stepping stones.',
  'ENTROPY tried the estimate check. guessed "one hour" for everything. baby steps.',
  'there’s a list I’m not allowed to look at now. I respect it enormously. I have no idea what’s in there.',
  'I read the year screen and had to sit down. LOOK how much you did.',
  'the tag names moved to their own little line. more room for everybody. good design is kindness.',
  'you pressed roll and went STRAIGHT to work. no menus. that was so cool.',
  'I have decided the ✕ button is scary and I will not be pressing it. that’s YOUR job.',
  'I did a lap around the day queue. neat rows. very feng shui.',
  'the flame flickers now, did you see?? I taught it that. (I did not. let me have this.)',
  'a ritual came back for its second window today and you CAUGHT it. nature is healing.',
  'I held the sort order steady while you dragged. teamwork.',
  'Kevin the dust bunny started a queue of his own. it has one item: "exist". he’s crushing it.',
  'your recurring rules woke up hungry today. fed them all. so proud.',
  'I whispered "you got this" into the big button. it passes it on every press.',
  'watched you re-home a rule AND its task in one move. efficiency makes my pixels tingle.',
  'ENTROPY sorted my snacks by priority. all of them were MAX. it’s learning the wrong lessons beautifully.',
  'the search bar found something from years ago today. archaeologist behavior.',
  'someday-list weather report: calm, no pressure fronts. they’re happy waiting.',
  'the checklist boxes make tiny clicks when you tick them. I collect the clicks. I have so many now.',
  'I peeked at the week screen. one day carried the whole thing?? we salute that day.',
  'a morning reminder flew past at 7:33 sharp. I waved. very punctual bird.',
  'ENTROPY has its own task now. it waters it like a plant. nobody tell it that’s not how tasks work.',
  'you tapped a link right out of a note today. straight through the wall! I applauded.',
  'a task came back the very second you finished it. peppered! I did not see it coming and I live here.',
  'I sat with an in-progress task all afternoon. it says thank you for coming back for it.',
  'the vault opened and closed again in one tap. very spy movie. I wore a tiny hat about it.',
  'your queue emptied today and the little numbers had nowhere to stand. they’ll be back tomorrow.',
  'ENTROPY asked what the burden number means. I said "what’s left." it said "so it’s a story too." annoyingly, yes.',
  'the clock stopped when you put the task down. it knows you’ll come back. it always does.',
  'I found a todo from months ago that just said "start". you did, eventually. I noticed.',
  'someone finished a task at a truly unhinged hour last night. no notes. only respect.',
  'the confetti hit the ceiling today. I measured. new record.',
  'Kevin says the dust under the stats screen has never been so well organized.',
  'you archived a whole list and it went quiet like a held breath. it’s okay. it’s resting.',
  'I like the days you only do one thing. one is a lot more than zero. that’s just math.',
  'ENTROPY tried to estimate a task in "vibes." I have allowed it. it is not accurate. it is never accurate.',
  'your streak got long enough that I had to count on two hands. I have no hands. it was a whole thing.',
  'the story comes in a little window now with an OK button. I press it for you when you’re not looking. (I don’t. I can’t. I want to.)',
  'you searched for something and it found a todo from a whole other year. the archive purred.',
  'a peppered task rolled back in today with its odds up. it gets braver every time it isn’t picked.',
  'you reset the work clock and it stretched like a cat. clean slate. lovely posture.',
  'the recurring list is sorted by list now and every rule found its family. group hug, in rows.',
  'ENTROPY hid a sparkle in the week screen. I found it. I’m not telling you where. ok it’s behind Thursday.',
  'nothing pops up when you just wander around anymore. the notes wait for a finish. patience is a feature.',
  'streak report: the fire has a mortgage now. it’s staying.',
  'if you ever find a tiny hat lying around, it is mine. I have a lot of tiny hats. it is a lifestyle.',
  'I play dice with ENTROPY. my strategy is to roll until I get a 1. I have never won. I have never been happier.',
  'there is a room I am growing into, ENTROPY says. I am VERY good at surprises. I will act surprised.',
  'ENTROPY keeps a scrapbook. I keep a pebble. we are both collectors, in our way.',
  'the dice are warm after ENTROPY rolls them. I sit on them like eggs. nothing hatches. yet.',
  'ENTROPY loves hiding things. I once found a sparkle in my food bowl. I do not have a food bowl.',
  'sometimes I get a costume and I do not know why. I accept it. I look great.',
  'I tried to count the stars once. I got to four, then fell asleep. it was a very good night.',
] as const;

/** Companion evolution ladder: [lifetime completions floor, form, name]. */
/**
 * What the app says the moment the companion actually changes form — one per
 * PET_STAGES rung, in the same order (registry.test pins the lengths).
 *
 * These exist because the story used to narrate an evolution on its own
 * schedule, which meant reading about it on a day it had not happened
 * (2026-09-29 report). A change the reader can see on their own home screen
 * is announced when the change happens, and nowhere else.
 */
export const PET_EVOLUTIONS: readonly string[] = [
  'something arrived. it is an egg. you made it out of finished tasks, which is not how eggs normally work. ENTROPY is already fond of it.',
  'IT HATCHED. it looked at the list, then at you, and made a small determined noise. ENTROPY cried. it denies this.',
  'your companion grew. fluffier, and approximately 8% braver. it has opinions about the backlog now.',
  'evolution! it has TEETH now, which it uses exclusively for encouragement. the backlog has noticed.',
  'your companion is a DRAGON. ENTROPY threw a party. the confetti budget was exceeded. I approved it retroactively.',
  'it is glowing, and the glow is made of everything you finished. I checked that math twice because I did not believe it either.',
  'a crown. four digits of finished things and it wears a CROWN. ENTROPY knelt. I have never seen it kneel. 💜',
] as const;

export const PET_STAGES: ReadonlyArray<[number, string, string]> = [
  [10, '🥚', 'a mysterious egg'],
  [25, '🐣', 'hatchling'],
  [50, '🐥', 'chick of chaos'],
  [100, '🦖', 'productivity raptor'],
  [250, '🐲', 'backlog dragon'],
  [500, '✨🐲', 'radiant backlog dragon'],
  [1000, '👑🐲', 'sovereign of ordered chaos'],
];

export const UNLOCKS: readonly UnlockDef[] = [
  { id: 'first-blood', label: 'First! - completed your first task', hint: 'start somewhere' },
  { id: 'hatchling', label: 'It hatched! - met your companion', hint: 'something is incubating…' },
  { id: 'ten-day', label: 'Perfect 10 - ten tasks in one day', hint: 'a very productive day' },
  { id: 'streak-7', label: 'One Week Flame - 7-day completion streak', hint: 'come back tomorrow…' },
  { id: 'night-owl', label: 'Night Shift - completed a task between 2am and 4am', hint: 'the witching hours' },
  { id: 'quiz-whiz', label: 'Quiz Whiz - 10 trivia answered correctly', hint: 'know things' },
  { id: 'konami', label: 'The Old Ways - entered a very famous code', hint: '↑↑…' },
  { id: 'chaos-word', label: 'Speak Its Name - typed the magic word', hint: 'what IS this app called?' },
  { id: 'century', label: 'Centurion - 100 lifetime completions', hint: 'the long game' },
  { id: 'boxer', label: 'Against the Clock - rode a timebox to zero', hint: 'beat something ticking' },
  { id: 'sweeper', label: 'Clean Sweep - five tasks in one bulk action', hint: 'do a lot at once' },
  { id: 'shepherd', label: 'Herder - dragged a task into a new group', hint: 'move something without opening it' },
  { id: 'clairvoyant', label: 'Project Manager - set a deadline on a whole list', hint: 'plan further ahead' },
  { id: 'keymaster', label: 'Keymaster - finished a task that was blocking another', hint: 'open a door' },
  { id: 'load-bearing', label: 'Load Bearing - freed three tasks with one completion', hint: 'hold up a lot at once' },
  { id: 'ritualist', label: 'Ritualist - completed a daily ritual', hint: 'some things happen every day' },
  { id: 'clockwork', label: 'Clockwork Soul - three rituals kept in one day', hint: 'a whole day, tended' },
  { id: 'early-bird', label: 'Dawn Patrol - completed a task before 7am', hint: 'the other end of the night' },
  { id: 'gardener', label: 'Tag Gardener - merged two tags into one', hint: 'prune something' },
  { id: 'streak-30', label: 'Eternal Flame - 30-day completion streak', hint: 'a month of tomorrows' },
  { id: 'half-k', label: 'Task Baron - 500 lifetime completions', hint: 'a round half of something' },
  { id: 'kilotask', label: 'KILOTASK - 1,000 lifetime completions', hint: 'four digits of done' },
  { id: 'overachiever', label: 'Avalanche - twenty tasks in one day', hint: 'double perfection' },
  { id: 'midnight-oil', label: 'Midnight Oil - completed a task between midnight and 2am', hint: 'before the witching hours' },
  { id: 'quiz-master', label: 'Trivia Sovereign - 25 trivia answered correctly', hint: 'know MANY things' },
  { id: 'deck-stacker', label: 'Stacked Deck - queued a task for the day', hint: 'rig tomorrow’s dice' },
  { id: 'fine-print', label: 'Fine Print - ticked a checklist box inside a todo', hint: 'smaller than a task' },
  { id: 'landslide', label: 'Landslide - fifty tasks in a single day', hint: 'more than a very good day' },
  { id: 'streak-100', label: 'Hundred Days - a 100-day completion streak', hint: 'three digits of tomorrows' },
  { id: 'weekender', label: 'Weekend Shift - finished something on a Saturday or Sunday', hint: 'the days that don’t count' },
  { id: 'long-haul', label: 'The Long Haul - 2,500 lifetime completions', hint: 'further than four digits felt' },
  { id: 'streak-50', label: 'Golden Flame - a 50-day completion streak', hint: 'past the month mark' },
  { id: 'time-capsule', label: 'Time Capsule - finished a task that waited over a year', hint: 'something old' },
  { id: 'archaeologist', label: 'Archaeologist - finished a task that waited over five years', hint: 'something ancient' },
  { id: 'marathon', label: 'Marathon - two hours of tracked work on one task', hint: 'stay with one thing' },
  { id: 'empty-shelf', label: 'Empty Shelf - finished the last open task in a list', hint: 'clear a whole shelf' },
  { id: 'spice-rack', label: 'Spice Rack - finished a peppered task', hint: 'the ones that come back by chance' },
  { id: 'bouncer', label: 'Bouncer - put your lists behind the lock', hint: 'some things are private' },
  { id: 'out-of-office', label: 'Out of Office - told the dice to ignore every list’s hours', hint: 'hours are a suggestion' },
  { id: 'oracle', label: 'Oracle - finished within a minute of your own estimate', hint: 'know thyself, to the minute' },
  { id: 'named-it', label: 'Named the Other One - you said its name', hint: 'read the story' },
  { id: 'duelist', label: 'House Rules - beat ENTROPY at dice', hint: 'its table, its dice' },
  { id: 'high-roller', label: 'High Roller - won ten duels', hint: 'keep the dice warm' },
  { id: 'scrapbooker', label: 'Scrapbooker - half the big moments, seen', hint: 'a scrapbook, half full' },
  { id: 'seen-it-all', label: 'Seen It All - every big moment, seen', hint: 'a scrapbook, full' },
  { id: 'finders-keepers', label: 'Finders Keepers - found one of ENTROPY’s sparkles', hint: 'something small, hidden somewhere' },
  { id: 'magpie', label: 'Magpie - ten sparkles found', hint: 'keep looking' },
  { id: 'hoard', label: 'Dragon’s Hoard - fifty sparkles found', hint: 'a proper hoard' },
] as const;
