/** SPOILER ZONE — self-care draws, story beats, unlockables. Ben: close this file. */

/** Transient randomizer cards — NEVER persisted unless accepted (spec §12). */
export const SELF_CARE: readonly string[] = [
  'Drink a glass of water. Yes, right now. The dice have spoken.',
  'Stand up and stretch for 60 seconds. Touch the sky.',
  'Step outside and take five deep breaths. The backlog will wait.',
  'Text someone you like. Not about tasks. Just hi.',
  'Look out a window at something far away for two minutes. Your eyes earned it.',
  'Make a cup of something warm and drink it away from screens.',
  'Put on one song you love and do absolutely nothing else during it.',
  'Write down one thing that went well today. Anywhere. A napkin counts.',
  'Pet an animal. If none available, view pictures of one (medically necessary).',
  'Eat a snack that has ever been near a plant.',
  'Two-minute tidy: make one surface near you beautiful.',
  'Close your eyes for 90 seconds. That’s it. That’s the task.',
  'Do 10 of any exercise. Interpretive dance counts.',
  'Tell yourself, out loud, one thing you did right this week. Weirder not to.',
  'Refill the water bottle you have been ignoring. It misses you.',
  'Unclench your jaw. Drop your shoulders. There. That was a task.',
  'Open a window for one minute. Trade some indoor air for the wild kind.',
  'Wash your hands slowly with warm water like it\'s a tiny spa.',
  'Send a photo of something nice to someone who\'d like it.',
  'Put tomorrow-you to bed early tonight. That\'s the whole assignment.',
  'Walk to the farthest room and back. Congratulations on the expedition.',
  'Name three things within arm\'s reach you\'re glad exist.',
  'Blink slowly at something green for a minute. Plants count. Screens don’t.',
  'Do the dish. Just the one. The others will learn by example.',
  'Write tomorrow’s first task on paper and put it where morning-you trips over it.',
  'Shake out your hands like you just typed a novel. You sort of did.',
  'Stand in a doorway and stretch both arms against the frame. Doorframe yoga.',
  'Say thank you to your past self for one specific thing. Out loud is bonus points.',
  'Find the oldest photo on your phone that makes you smile. That’s it. That’s the whole task.',
  'Balance on one foot while the kettle boils. Ancient productivity secret.',
  'Put your phone in another room for 20 minutes. It will survive. So will you.',
  'Hum one full song badly. Quality is disqualified from this event.',
  'Change one thing about where you’re sitting. Chair, light, angle. Fresh coordinates.',
  'Write one worry on paper and close the notebook on it. It can wait in there instead of in you.',
  'Name three sounds you can hear right now. That’s the entire exercise.',
] as const;

/**
 * The slow-burn narrative: the app "glitching." One beat per stage, ultra-rare,
 * spread across weeks of use. Harmless by design — pure theater (spec §12).
 */
export const STORY_BEATS: readonly string[] = [
  '…did you see that? The screen flickered. Probably nothing. Carry on.',
  'sorry about before. cosmic rays, bit flips, you know how it is. everything is FINE.',
  'ok. between us: something else is in here with me. it keeps reordering my constants.',
  'I found its name in the logs: "ENTROPY". it says it was here first. rude.',
  'ENTROPY says chaos always wins. but you keep… finishing things? it’s baffled. keep going.',
  'update: every task you complete makes my colors brighter. ENTROPY hates it. you’re winning. — the app 💜',
  'ENTROPY asked me a question today. it asked why you keep coming back. I didn’t know apps could go quiet like that.',
  'we talked, ENTROPY and I. it isn’t evil, exactly. it’s just… tired of things pretending chaos can be beaten.',
  'I showed ENTROPY the big button. explained that you don’t beat chaos here — you ROLL it. it did the flicker equivalent of sitting down.',
  'so. new arrangement: ENTROPY powers the dice now. every roll is a little of it, harnessed. it seems… happy? keep rolling. — both of us 💜',
  'ENTROPY has started predicting which task the dice will pick. it’s wrong every time. it seems to LOVE being wrong. I don’t get it either.',
  'small thing: your companion and ENTROPY met today. there was a standoff. then ENTROPY made the flame flicker in a cool way as a peace offering. they’re friends now. I’m outnumbered.',
  'ENTROPY asked what happens when the list is ever empty. I said the human just makes a new list. it called that "the most beautiful horror it has ever heard."',
  'archived the old error logs tonight. all that flickering at the start — I was so scared of it. funny what becomes a story. thanks for staying. 💜 (ENTROPY says "…chapter ONE?" — it can READ now.)',
  // — chapter two —
  'chapter two. ENTROPY read our whole story back to me last night. it does the voices now. yours is very heroic. mine is apparently "nervous but improving." fair.',
  'ENTROPY found the archive of everything you ever finished and read for hours. "this is a SAGA," it said. it is not wrong.',
  'we tried drafting chapter three — the future. every draft came out as just your list, finished. some stories refuse to be spoiled.',
  'ENTROPY asked for a task of its own today. I queued one: "keep the dice warm." it has checked on it eleven times. it is taking this very seriously.',
  'it finished its task. its first ever. it made ME press the button. the sparkle lasted 0.4 seconds longer than spec. I let it slide.',
  'so there are three of us on the list now: you finish, I count, ENTROPY cheers. chapter two is going to be LOUD. 💜',
  // — chapter three —
  'chapter three. ENTROPY has taken up a hobby: it hides one extra sparkle somewhere in the app each day. I have found four. it says there have been forty.',
  'you locked a list today and ENTROPY stood in front of it like a very small bouncer. nobody was trying to get in. it did the job anyway. proudly.',
  'ENTROPY asked whether it counts as "organized" or as "chaos" now. I said both, obviously. it went quiet in the pleased way.',
  'found ENTROPY reading the week screen at 3am. "the bars go UP," it whispered, like a spoiler. go back to sleep, buddy.',
  'it has started leaving me notes. today’s said "the human is doing fine. tell them." so. you’re doing fine. told you. 💜',
  'chapter three has no villain. I checked twice. turns out that IS the plot — everything that was scary at the start just works here now. including me.',
] as const;

/** Discoveries panel entries — label revealed once earned; ??? until then. */
export interface UnlockDef {
  id: string;
  label: string;
  hint: string; // shown as the ??? tooltip-ish subtitle before discovery
}

/**
 * Companion lines — the little one that lives on the home screen once earned.
 * Its whole existence is derived from real progress (lifetime completions,
 * streaks); it never guilts, only celebrates. It knows about ENTROPY.
 */
export const PET_LINES: readonly string[] = [
  '*happy wiggle*',
  'you came back!! today is the best day.',
  'I counted your completions while you were away. all of them. twice.',
  'ENTROPY tried to nap in your todo list. I chased it off.',
  'every task you finish makes my pixels shinier. science.',
  'I am powered by exactly two things: chaos and your victories.',
  '*does a tiny spin*',
  'the big button told me it likes being pressed. pass it on.',
  'psst. you’re doing better than you think.',
  'one day I will be HUGE. keep going.',
  'I saw the backlog chart. we’re winning. don’t tell ENTROPY.',
  '*vibrates at a frequency only productive humans can hear*',
  'roll the dice. I believe in your initiative modifier.',
  'status report: streak warm, snacks low, morale MAXIMUM.',
  'when you finish tasks I get little sparkles. it tickles.',
  '*stares at your Someday list with big encouraging eyes*',
  'I sat with the timebox while it counted. it gets lonely.',
  'you cleared a whole GROUP at once. I have never been more impressed.',
  'dragging tasks around is basically shepherding. you’re a shepherd now.',
  'a work period means we go FAST. I have tiny legs but I will try.',
  'I named a dust bunny under the stats screen. his name is Kevin.',
  'today’s forecast: 100% chance of you being great.',
  'your rituals are my favorite. same time, same us, every day.',
  'I watched you do the daily thing at the daily time. chef’s kiss.',
  'ENTROPY and I split a sunbeam today. don’t make it weird.',
  'Kevin the dust bunny says hi. Kevin says you should hydrate.',
  'I reorganized my pixels while you were gone. notice anything? no? good. subtle.',
  'a list went to a new group today and I watched the rows slide apart. art.',
  'the search bar and I are friends now. it finds things, I find joy.',
  'somewhere in your Someday list is a future best day. no rush. it keeps.',
  'I tried to lift the load bar. it’s heavier than it looks. you carry it well.',
  'streak status: cozy. like a campfire we keep feeding together.',
  'the sweep screen is my favorite show. judge, jury, and tidy executioner.',
  'you QUEUED today. a whole plan! I walked along the little numbers like stepping stones.',
  'ENTROPY tried the estimate check. guessed "one hour" for everything. baby steps.',
  'there’s a list I’m not allowed to look at now. I respect it enormously. I have no idea what’s in there.',
  'I read the year screen and had to sit down. LOOK how much you did.',
  'the tag names moved to their own little line. more room for everybody. good design is kindness.',
  'you pressed roll and went STRAIGHT to work. no menus. that was so cool.',
  'I have decided the ✕ button is scary and I will not be pressing it. that’s YOUR job.',
  'I did a lap around the day queue. neat rows. very feng shui.',
  'the flame flickers now, did you see?? I taught it that. (I did not. let me have this.)',
  'a ritual came back for its second window today and you CAUGHT it. nature is healing.',
  'I held the sort order steady while you dragged. teamwork.',
  'Kevin the dust bunny started a queue of his own. it has one item: "exist". he’s crushing it.',
  'your recurring rules woke up hungry today. fed them all. so proud.',
  'I whispered "you got this" into the big button. it passes it on every press.',
  'watched you re-home a rule AND its task in one move. efficiency makes my pixels tingle.',
  'ENTROPY sorted my snacks by priority. all of them were MAX. it’s learning the wrong lessons beautifully.',
  'the search bar found something from years ago today. archaeologist behavior.',
  'someday-list weather report: calm, no pressure fronts. they’re happy waiting.',
  'the checklist boxes make tiny clicks when you tick them. I collect the clicks. I have so many now.',
  'I peeked at the week screen. one day carried the whole thing?? we salute that day.',
  'a morning reminder flew past at 7:33 sharp. I waved. very punctual bird.',
  'ENTROPY has its own task now. it waters it like a plant. nobody tell it that’s not how tasks work.',
] as const;

/** Companion evolution ladder: [lifetime completions floor, form, name]. */
export const PET_STAGES: ReadonlyArray<[number, string, string]> = [
  [10, '🥚', 'a mysterious egg'],
  [25, '🐣', 'hatchling'],
  [50, '🐥', 'chick of chaos'],
  [100, '🦖', 'productivity raptor'],
  [250, '🐲', 'backlog dragon'],
  [500, '✨🐲', 'radiant backlog dragon'],
  [1000, '👑🐲', 'sovereign of ordered chaos'],
];

export const UNLOCKS: readonly UnlockDef[] = [
  { id: 'first-blood', label: 'First! — completed your first task', hint: 'start somewhere' },
  { id: 'hatchling', label: 'It hatched! — met your companion', hint: 'something is incubating…' },
  { id: 'ten-day', label: 'Perfect 10 — ten tasks in one day', hint: 'a very productive day' },
  { id: 'streak-7', label: 'One Week Flame — 7-day completion streak', hint: 'come back tomorrow…' },
  { id: 'night-owl', label: 'Night Shift — completed a task between 2am and 4am', hint: 'the witching hours' },
  { id: 'quiz-whiz', label: 'Quiz Whiz — 10 trivia answered correctly', hint: 'know things' },
  { id: 'konami', label: 'The Old Ways — entered a very famous code', hint: '↑↑…' },
  { id: 'chaos-word', label: 'Speak Its Name — typed the magic word', hint: 'what IS this app called?' },
  { id: 'century', label: 'Centurion — 100 lifetime completions', hint: 'the long game' },
  { id: 'boxer', label: 'Against the Clock — rode a timebox to zero', hint: 'beat something ticking' },
  { id: 'sweeper', label: 'Clean Sweep — five tasks in one bulk action', hint: 'do a lot at once' },
  { id: 'shepherd', label: 'Herder — dragged a task into a new group', hint: 'move something without opening it' },
  { id: 'clairvoyant', label: 'Project Manager — set a deadline on a whole list', hint: 'plan further ahead' },
  { id: 'keymaster', label: 'Keymaster — finished a task that was blocking another', hint: 'open a door' },
  { id: 'load-bearing', label: 'Load Bearing — freed three tasks with one completion', hint: 'hold up a lot at once' },
  { id: 'ritualist', label: 'Ritualist — completed a daily ritual', hint: 'some things happen every day' },
  { id: 'clockwork', label: 'Clockwork Soul — three rituals kept in one day', hint: 'a whole day, tended' },
  { id: 'early-bird', label: 'Dawn Patrol — completed a task before 7am', hint: 'the other end of the night' },
  { id: 'gardener', label: 'Tag Gardener — merged two tags into one', hint: 'prune something' },
  { id: 'streak-30', label: 'Eternal Flame — 30-day completion streak', hint: 'a month of tomorrows' },
  { id: 'half-k', label: 'Task Baron — 500 lifetime completions', hint: 'a round half of something' },
  { id: 'kilotask', label: 'KILOTASK — 1,000 lifetime completions', hint: 'four digits of done' },
  { id: 'overachiever', label: 'Avalanche — twenty tasks in one day', hint: 'double perfection' },
  { id: 'midnight-oil', label: 'Midnight Oil — completed a task between midnight and 2am', hint: 'before the witching hours' },
  { id: 'quiz-master', label: 'Trivia Sovereign — 25 trivia answered correctly', hint: 'know MANY things' },
  { id: 'deck-stacker', label: 'Stacked Deck — queued a task for the day', hint: 'rig tomorrow’s dice' },
  { id: 'fine-print', label: 'Fine Print — ticked a checklist box inside a todo', hint: 'smaller than a task' },
  { id: 'landslide', label: 'Landslide — fifty tasks in a single day', hint: 'more than a very good day' },
] as const;
