/** SPOILER ZONE — content pool. Ben: close this file. */
export const FACTS: readonly string[] = [
  'Octopuses have three hearts, and two of them stop beating when they swim.',
  'Honey never spoils — edible honey has been found in 3,000-year-old Egyptian tombs.',
  "A day on Venus is longer than its year.",
  'Wombat poop is cube-shaped so it doesn’t roll off rocks.',
  'Sharks existed before trees. And before Saturn’s rings.',
  'Your body contains about 0.2 milligrams of gold, mostly in your blood.',
  'A cloud can weigh more than a million pounds.',
  'Sea otters hold hands while sleeping so they don’t drift apart.',
  'The Eiffel Tower grows about 15 cm taller in summer heat.',
  'Hot water can freeze faster than cold water. Nobody fully knows why.',
  'A group of flamingos is called a "flamboyance."',
  'Neutron star material weighs about a billion tons per teaspoon.',
  'The inventor of the Pringles can is buried in one.',
  'Some turtles can breathe through their butts.',
  'Oxford University is older than the Aztec Empire.',
  'Sloths can hold their breath longer than dolphins — up to 40 minutes.',
  'Lightning strikes Earth about 8 million times per day.',
  'The human brain uses roughly 20 watts — a dim lightbulb running your whole life.',
  'Tardigrades can survive the vacuum of space, boiling, freezing, and radiation.',
  'A bolt of lightning is five times hotter than the surface of the sun.',
  'Axolotls can regrow limbs, spinal cord, heart tissue, and parts of their brain.',
  'The Great Wall of China is not visible from space with the naked eye. Sorry.',
  'Cleopatra lived closer in time to the Moon landing than to the Great Pyramid.',
  'There’s enough DNA in your body to stretch to the sun and back 60+ times.',
  'Bees can recognize human faces.',
  'The word "robot" comes from the Czech "robota," meaning forced labor.',
  'Antarctica is the largest desert on Earth.',
  'A jiffy is a real unit of time: 1/100th of a second (or one light-cm in physics).',
  'Ravens can hold grudges against specific humans for years.',
  'The Sahara was green with lakes and hippos just 6,000 years ago.',
  'Some metals, like gallium, melt in your hand.',
  'Butterflies taste with their feet.',
  'The mantis shrimp punches with the acceleration of a .22 caliber bullet.',
  'Space smells like seared steak and hot metal, according to astronauts.',
  'The longest recorded flight of a chicken is 13 seconds.',
  'Venus is the only planet that spins clockwise.',
  'An octopus has nine brains — one central, one per arm.',
  'Humans share about 60% of their DNA with bananas.',
  'The Moon has moonquakes.',
  'Cats can’t taste sweetness.',
  'A single strand of spaghetti is called a "spaghetto."',
  'The heart of a blue whale is the size of a small car.',
  'Finland has more saunas than cars.',
  'The dot over a lowercase i is called a "tittle."',
  'Roman concrete gets STRONGER over time; ours cracks. We finally learned why in 2023.',
  'Water bears aside, the immortal jellyfish can age backwards indefinitely.',
  'Polar bear skin is black. Their fur is transparent, not white.',
  'The Ottoman Empire still existed the last time the Cubs had won the World Series (1908→2016).',
  'A teaspoonful of soil contains more living organisms than there are humans on Earth.',
  'Sound travels four times faster underwater.',
  'Giraffes only need 30 minutes to 2 hours of sleep per day.',
  'The first computer "bug" was an actual moth, taped into a 1947 logbook.',
  'Nintendo was founded in 1889 — it made playing cards for 60+ years first.',
  'The average cumulus cloud contains about 500 tons of water, floating.',
  'Hippos produce their own pink sunscreen.',
  'Saturn would float in a big enough bathtub — it’s less dense than water.',
  'Your stomach gets a new lining every few days so it doesn’t digest itself.',
  'Alaska is simultaneously the westernmost AND easternmost US state.',
  'Dead skin makes up about half of household dust. You’re welcome.',
  'Crows have funerals — they gather around their dead to learn what happened.',
  'The plastic tips of shoelaces are called "aglets."',
  'Armadillos almost always give birth to identical quadruplets.',
  'A day is getting ~1.8 milliseconds longer per century as the Moon drifts away.',
  'Snails can sleep for up to three years.',
  'The Mona Lisa has no eyebrows.',
  'There are more trees on Earth than stars in the Milky Way.',
  'A "moment" was a medieval unit of time: exactly 90 seconds.',
  'Koalas have fingerprints nearly identical to humans — enough to confuse crime scenes.',
  'The shortest war in history lasted 38 minutes (Britain vs. Zanzibar, 1896).',
  'Pigeons can learn to distinguish Monet from Picasso.',
  'The Sun makes up 99.86% of the mass of the solar system.',
  'One million Earths would fit inside the Sun. It is an average-sized star.',
  'Peanuts aren’t nuts. They’re legumes. Cashews grow on the bottom of a fruit.',
  'Sea cucumbers can eject their internal organs as a defense, then regrow them.',
  'Iceland has no mosquitoes. Zero.',
  'The typical pencil can draw a line 35 miles long.',
  'Norway once knighted a penguin. Sir Nils Olav III, Colonel-in-Chief.',
  'Some cats are allergic to humans.',
  'The observable universe contains more stars than grains of sand on all Earth’s beaches.',
  'The @ symbol is called a "snabel-a" (elephant trunk A) in Danish.',
  'Bananas are berries. Strawberries are not.',
  'There are more possible chess games than atoms in the observable universe.',
  'Scotland’s national animal is the unicorn.',
  'Your body’s atoms are mostly empty space — compress it out and humanity fits in a sugar cube.',
  'Jupiter’s Great Red Spot is a storm that’s raged for at least 190 years.',
  'Reindeer eyes turn blue in winter to see better in the dark.',
  'The average person walks the equivalent of three times around the world in a lifetime.',
  'The Boston Molasses Flood of 1919 moved at 35 mph and was deadlier than it sounds.',
  'Frogs can freeze solid in winter and thaw back to life in spring.',
  'The Library of Alexandria’s biggest losses came from budget cuts, not one fire.',
  'A shrimp’s heart is in its head.',
  'Dolphins have names for each other — signature whistles.',
  'Mount Everest grows about 4mm taller every year.',
  'You can’t hum while holding your nose. You just tried.',
  'Bubble wrap was originally invented as wallpaper.',
  'An adult human is, briefly, a single cell. Everyone you know passed through that bottleneck.',
  'Wind turbines can’t be painted just any color — one black blade cuts bird deaths ~70%.',
  'The word "set" has more definitions than any other English word — over 400.',
  'Fungal networks connect forest trees and shuttle nutrients between them.',
  'Vending machines are statistically deadlier than sharks.',
  'The first oranges weren’t orange — they were green.',
  'A hummingbird’s heart can beat over 1,200 times a minute.',
  'The Eiffel Tower was meant to be dismantled after 20 years — radio saved it.',
  'Sweden has a rabbit show-jumping league called Kaninhoppning.',
  'The unicode snowman ☃ has an official "black snowman" sibling: ⛇.',
  'Your left lung is smaller than your right to make room for your heart.',
  'The Atlantic Ocean grows about 4 cm wider every year.',
  'Medieval manuscripts are full of doodles of snails fighting knights. Nobody knows why.',
  'A single lightning bolt could toast about 100,000 slices of bread.',
  'The Netherlands sends Canada 20,000 tulip bulbs every year, since 1945.',
  'Honeybees can get "waggle dance" dialects wrong — foreign bees misread directions.',
  'The moon is slowly leaving. About 3.8 cm a year. It’s not personal.',
  'Some clownfish change sex when the group needs a new female. Finding Nemo lied.',
  'The hashtag symbol is technically called an "octothorpe."',
  'Firefighters in ancient Rome were also the demolition crew — often of your house.',
  'A blue whale’s tongue weighs as much as an elephant.',
  'Carrots were mostly purple until Dutch growers bred the orange ones.',
  'The first alarm clock could only ring at 4 a.m.',
  'Owls can’t move their eyes — that’s why the head does all the work.',
  'The Spanish national anthem has no official lyrics.',
  'Wombats are surprisingly fast: 40 km/h in a sprint. Cube engines.',
  'Every ‘o’ in Google’s original logo was almost a different primary color scheme.',
  'Astronauts grow up to 5 cm taller in space, then shrink back on Earth.',
  'Ketchup was sold as medicine in the 1830s.',
  'The fax machine predates the telephone by about a decade.',
  'A cat’s nose print is unique, like a fingerprint.',
  'The Great Barrier Reef is the largest structure ever built by living things.',
  'There’s a species of jellyfish with 24 eyes and no brain to watch through them.',
  'Roughly 1% of old TV static was the afterglow of the Big Bang.',
  'The inventor of the frisbee was cremated and made into frisbees.',
  'Sea sponges have no organs at all and can reassemble after being strained through cloth.',
  'The word "checkmate" comes from Persian: "shah mat" — the king is helpless.',
  'An adult’s blood vessels, laid end to end, would circle Earth twice.',
  'Pineapples take about two years to grow. Respect the fruit.',
  'The lighter was invented before the match.',
  'Squirrels forget where they buried billions of nuts a year — accidental foresters.',
  'The North Star will retire: Vega takes the job in about 12,000 years.',
  'A bolt of cloth and a bolt of lightning share a root: both "shoot out."',
  'Some Roman roads are still in use, 2,000 years of traffic later.',
  'The average lead pencil isn’t lead and never was — always graphite.',
  'Camels have three eyelids per eye. Deserts demand redundancy.',
  'The first webcam watched a coffee pot at Cambridge so nobody walked to an empty one.',
  'Rain has a smell with a name: petrichor — oils from dry ground meeting water.',
  'Newborn kangaroos are the size of a jellybean.',
  'The longest place name in the world has 85 letters and lives in New Zealand.',
  'Glass balls bounce higher than rubber balls of the same size.',
  'Wombat droppings are cubes. The shape stops them rolling off the rocks they mark.',
  'A mantis shrimp punches fast enough to boil a little water around its own claw.',
  'Olympus Mons on Mars is so wide that standing on it, you couldn’t tell it was a mountain.',
  'The first computer "bug" was a literal moth, taped into a 1947 logbook.',
  'Sloths can take up to a month to digest one leaf. Deliberate is a lifestyle.',
  'The dot over an i or j has a name: a tittle.',
  'Venus has no moons, no seasons, and days longer than its years. Nothing there works.',
  'Otters keep a favourite rock in a pocket of loose skin under the arm.',
  'Bamboo can grow nearly a metre in a day. Some of it is audibly growing.',
] as const;
