/** SPOILER ZONE — content pool. Ben: close this file. */

/** Short celebratory / referential one-liners shown on completions and rolls. */
export const QUIPS: readonly string[] = [
  'IT’S OVER 9000!!! (your productivity, probably)',
  'A winner is you.',
  'Task defeated. You gained 34 XP.',
  'Achievement unlocked: literally doing the thing',
  'GG EZ. Well, maybe not EZ. GG though.',
  'The cake may be a lie, but this completion is real.',
  'You have died of dysentery— wait, no, you finished a task. Nice.',
  'Hey! Listen! …that was great.',
  'Do a barrel roll! 🛢️',
  'It’s dangerous to go alone — take this ✓',
  'All your task are belong to us.',
  'FINISH HIM. …you did. Flawless victory.',
  'You’re winner!',
  'Snake? Snake?! SNAAAAKE— oh you’re fine, task’s done.',
  'The princess is in another castle, but this task is DONE.',
  'Wow. Much productive. Very task. So done.',
  '*teleports behind your todo list* nothing personnel, kid',
  'This one sparks joy. The task, gone. The joy, yours.',
  'One does not simply finish a task. And yet.',
  'You shall not… oh, you already passed. Carry on.',
  'roll_credits.mp4',
  'Task complete. Sekiro voice: "Shinobi Execution."',
  'EXCELLENT. *air guitar*',
  'Kept you waiting, huh?',
  'War. War never changes. Todo lists, though — those shrink.',
  'Praise the sun! \\[T]/',
  'YOU DIED — jk, the task did.',
  'Hadouken’d that one straight off the list.',
  'Objective complete. +100 rep with [Yourself].',
  'The right man in the wrong place can make all the difference in the world.',
  'Stay awhile and listen: you did good.',
  'It’s super effective!',
  'A wild PRODUCTIVITY appeared!',
  'Gotta catch ’em all — the tasks, that is.',
  '*Metal Gear alert noise* !  — they noticed how productive you are',
  'Would you kindly… keep crushing it?',
  'Mission passed! Respect +',
  'The numbers, Mason! They’re going DOWN! (your open task count)',
  'Big brain time.',
  'Poggers.',
  'Certified hood classic (the task is done)',
  'You just got Vectored ➡️ (into productivity)',
  'Never gonna give you up, never gonna let your streak down 🎵',
  'This is the way.',
  'I used the tasks to destroy the tasks.',
  'Perfectly balanced, as all todo lists should be.',
  'You’re breathtaking!',
  'Not all heroes wear capes. Some just do the dishes.',
  'somebody once told me the task was gonna roll me 🎵 (it didn’t)',
  'You’ve yeed your last haw, task.',
  'And they don’t stop coming and they don’t stop coming 🎵',
  'Directed by Robert B. Weide 🎵 (your task’s outro)',
  'Curiosity killed the task.',
  'sudo rm -rf ./doubts',
  '// TODO: nothing. It’s done.',
  'exit code 0. clean.',
  '99 little bugs in the code… wait, wrong app.',
  'git push --force through the day',
  'Your PR to reality has been merged.',
  'Segfault? Never met her.',
  'while(true){ win(); }',
  'Cache invalidated: the excuse cache.',
  'It compiles AND ships. Rare W.',
  'Rubber duck says: quack (proud of you)',
  'Works on MY machine — and yours, apparently.',
  'Tabs, spaces — who cares, the task is DONE.',
  'You absolute legend.',
  'Nice. 😎',
  'The grind is grinding.',
  'Certified fresh. 100% on Rotten Tomatoes.',
  'In a world… where tasks got done… one hero rose.',
  'Meanwhile, at the Legion of Doom: "curses, they’re being productive."',
  'With great power comes great responsi— you know the rest. You lived it.',
  'BAM! POW! (comic book noises of productivity)',
  'Kneel before your completed task. Or don’t. It’s done either way.',
  'Task: I’m about to end this whole man’s— *task gets completed*',
  'Emotional damage! (to the backlog)',
  'The prophecy is fulfilled.',
  'Your ancestors are smiling at you, Imperial. Can you say the same?',
  'Roll for initiative. Natural 20. Obviously.',
  'The dice giveth, and you taketh care of business.',
  'Critical hit! ×2 productivity damage.',
  'Bard-level charisma, rogue-level efficiency.',
  'Strong Bad would’ve deleted this task. You FINISHED it. Growth.',
  'DELETED!! …the task, lovingly.',
  'Trogdor the BURNINATOR approves of this burnination of your backlog.',
] as const;

/** Lines for finishing (or surviving) a timebox. */
export const TIMEBOX_LINES: readonly string[] = [
  'Time. Pencils down. 📝',
  'BRRRING. That’s the round.',
  'The timer has spoken. You may now stretch.',
  'Ding! Your table is ready — table for one, at the couch.',
  '⏰ Deploy complete. Rolling back to rest state.',
  'That’s a wrap on this scene.',
  'Boss defeated: The Ticking Clock.',
  'You have been timeboxed. How do you feel?',
  'Focus streak ended by natural causes.',
  'The sand has run out. Flip me over anytime.',
  'Pomodoro achieved. Tomato acquired. 🍅',
  'GG. The clock never stood a chance.',
] as const;

/** Lines for declaring a work period. */
export const WORK_PERIOD_LINES: readonly string[] = [
  'Clock in. ⏱ Let’s make it count.',
  'Deep work mode: engaged.',
  'The gauntlet is set. Only what fits gets through.',
  'Focus window open. Distractions, form an orderly queue.',
  'Speedrun timer started. Any%.',
  'Right then. Sleeves: rolled.',
  'The forge is hot.',
] as const;

/** Lines for sweeping several tasks at once. */
export const BULK_LINES: readonly string[] = [
  'Multi-kill! 💥',
  'A clean sweep. Very satisfying.',
  'Batch processed. Efficiency: unreasonable.',
  'You just did that in bulk. Costco energy.',
  'Mass deletion of obligations. Gorgeous.',
  'That was a combo, and I saw it.',
  'Ah, the ol’ select-and-obliterate. A classic.',
] as const;

/** Rarer streak / heater lines — the app noticing you’re on one. */
export const STREAK_LINES: readonly string[] = [
  '🔥 You’re on fire. (metaphorically. hydrate.)',
  '🔥🔥 HEATER. The dice fear you.',
  'You’ve entered THE ZONE. Please keep arms and legs inside the flow state.',
  'Combo ×3! The announcer is losing their mind.',
  'C-C-C-COMBO BREAKER — is what your streak does to procrastination.',
  'The backlog is scared of you today.',
  'Are you… speedrunning your life? Splits look great.',
  'New personal best pace. The ghost car is way behind.',
  'M-M-M-MONSTER STREAK.',
  'The productivity gods demand nothing. They’re just impressed.',
] as const;
