/** SPOILER ZONE — content pool. Ben: close this file. */

/** Short celebratory / referential one-liners shown on completions and rolls. */
export const QUIPS: readonly string[] = [
  'IT’S OVER 9000!!! (your productivity, probably)',
  'A winner is you.',
  'Task defeated. You gained 34 XP.',
  'Achievement unlocked: literally doing the thing',
  'GG EZ. Well, maybe not EZ. GG though.',
  'The cake may be a lie, but this completion is real.',
  'You have died of dysentery— wait, no, you finished a task. Nice.',
  'Hey! Listen! …that was great.',
  'Do a barrel roll! 🛢️',
  'It’s dangerous to go alone — take this ✓',
  'All your task are belong to us.',
  'FINISH HIM. …you did. Flawless victory.',
  'You’re winner!',
  'Snake? Snake?! SNAAAAKE— oh you’re fine, task’s done.',
  'The princess is in another castle, but this task is DONE.',
  'Wow. Much productive. Very task. So done.',
  '*teleports behind your todo list* nothing personnel, kid',
  'This one sparks joy. The task, gone. The joy, yours.',
  'One does not simply finish a task. And yet.',
  'You shall not… oh, you already passed. Carry on.',
  'roll_credits.mp4',
  'Task complete. Sekiro voice: "Shinobi Execution."',
  'EXCELLENT. *air guitar*',
  'Kept you waiting, huh?',
  'War. War never changes. Todo lists, though — those shrink.',
  'Praise the sun! \\[T]/',
  'YOU DIED — jk, the task did.',
  'Hadouken’d that one straight off the list.',
  'Objective complete. +100 rep with [Yourself].',
  'The right man in the wrong place can make all the difference in the world.',
  'Stay awhile and listen: you did good.',
  'It’s super effective!',
  'A wild PRODUCTIVITY appeared!',
  'Gotta catch ’em all — the tasks, that is.',
  '*Metal Gear alert noise* !  — they noticed how productive you are',
  'Would you kindly… keep crushing it?',
  'Mission passed! Respect +',
  'The numbers, Mason! They’re going DOWN! (your open task count)',
  'Big brain time.',
  'Poggers.',
  'Certified hood classic (the task is done)',
  'You just got Vectored ➡️ (into productivity)',
  'Never gonna give you up, never gonna let your streak down 🎵',
  'This is the way.',
  'I used the tasks to destroy the tasks.',
  'Perfectly balanced, as all todo lists should be.',
  'You’re breathtaking!',
  'Not all heroes wear capes. Some just do the dishes.',
  'somebody once told me the task was gonna roll me 🎵 (it didn’t)',
  'You’ve yeed your last haw, task.',
  'And they don’t stop coming and they don’t stop coming 🎵',
  'Directed by Robert B. Weide 🎵 (your task’s outro)',
  'Curiosity killed the task.',
  'sudo rm -rf ./doubts',
  '// TODO: nothing. It’s done.',
  'exit code 0. clean.',
  '99 little bugs in the code… wait, wrong app.',
  'git push --force through the day',
  'Your PR to reality has been merged.',
  'Segfault? Never met her.',
  'while(true){ win(); }',
  'Cache invalidated: the excuse cache.',
  'It compiles AND ships. Rare W.',
  'Rubber duck says: quack (proud of you)',
  'Works on MY machine — and yours, apparently.',
  'Tabs, spaces — who cares, the task is DONE.',
  'You absolute legend.',
  'Nice. 😎',
  'The grind is grinding.',
  'Certified fresh. 100% on Rotten Tomatoes.',
  'In a world… where tasks got done… one hero rose.',
  'Meanwhile, at the Legion of Doom: "curses, they’re being productive."',
  'With great power comes great responsi— you know the rest. You lived it.',
  'BAM! POW! (comic book noises of productivity)',
  'Kneel before your completed task. Or don’t. It’s done either way.',
  'Task: I’m about to end this whole man’s— *task gets completed*',
  'Emotional damage! (to the backlog)',
  'The prophecy is fulfilled.',
  'Your ancestors are smiling at you, Imperial. Can you say the same?',
  'Roll for initiative. Natural 20. Obviously.',
  'The dice giveth, and you taketh care of business.',
  'Critical hit! ×2 productivity damage.',
  'Bard-level charisma, rogue-level efficiency.',
  'Strong Bad would’ve deleted this task. You FINISHED it. Growth.',
  'DELETED!! …the task, lovingly.',
  'Trogdor the BURNINATOR approves of this burnination of your backlog.',
  'Another one bites the dust. The dust is thriving.',
  'That task talked a big game. You ended the conversation.',
  'Somewhere, a project manager just felt a chill of pride.',
  'The done pile grows. The done pile is beautiful.',
  'You vs. the backlog: currently winning on points.',
  'Crossed off with EXTREME prejudice.',
  'One small tick for you, one giant leap for the list.',
  'The chaos has been consulted. It approves.',
  'Efficiency? In THIS economy? Incredible.',
  'Task down. Swagger up.',
  'Your future self just sent a thank-you note.',
  'Executed flawlessly. The witnesses (me) were impressed.',
  'The council of dice has reviewed your work. Verdict: magnificent.',
  'Somewhere a whiteboard just gained a checkmark out of respect.',
  'Speedran that errand like it owed you money.',
  'Task status: extremely former.',
  'The backlog just updated its threat assessment. You’re listed.',
  'Achievement synced to the cloud (the emotional one).',
  'Ding! Level up. Skill points allocated to Getting Things Done.',
  'That was textbook. They should teach that completion in schools.',
  'The item has been crafted. The recipe was courage.',
  'Fus Ro DONE.',
  'Enemies defeated: 1 (it was a chore).',
  'You looked at entropy and said "not today." Verifiably.',
  'The simulation devs are patching you next release — too strong.',
  'S-rank clear. No continues used.',
  'Your todo list called. It’s scared. Good.',
  'Quest complete. Reward: one (1) smug little glow.',
  'Waluigi time? No. YOUR time.',
  'Another brick out of the wall of doom.',
  'Task retired with full honors and a tiny parade.',
  'Chaos looked away for ONE second and you finished a thing.',
  'The estimate feared you. Rightly.',
  'Absolutely no notes. Ship it.',
  'That’s going in the highlight reel.',
  'Legend says the task is still completed to this day.',
  'You pressed the button of destiny and destiny blinked.',
  'Inventory updated: −1 burden, +1 swagger.',
  'The little checkbox dreamed of this day.',
  'Frame-perfect execution. TAS bot is taking notes.',
  'Objective marker cleared. New waypoint pending.',
  'The respawn timer on your motivation: instant, apparently.',
  'Combo meter rising. Style rank: S for "did the thing".',
  'You dodge-rolled procrastination with perfect i-frames.',
  'Checkpoint reached. Progress saved to the cloud AND your soul.',
  'Rip and tear, until it is done. (It is done.)',
  'The road ahead was full of tasks. You mario-karted through.',
  'Sidequest complete! Main quest morale +10.',
  'No skill tree needed — you unlocked that one with sheer spite.',
  'Boss phase two never came. You ended it in phase one.',
  'Finish the fight. …you just did. Welcome home.',
  'Hey, you. You’re finally awake. And suspiciously productive.',
  'Star acquired. ⭐ Course cleared.',
  'You stayed determined. The task did not.',
  'The party gains 250 gold and a rumor about the next quest.',
  'That one had i-frames. You hit it anyway.',
  'New high score on the oldest arcade cabinet: Real Life.',
  'The minimap shows nothing left in this zone. Clean clear.',
  'Fast travel unlocked: straight past that task forever.',
  'The credits aren’t rolling because you’re clearly not done being great.',
  'Task deleted from reality. No save scumming it back.',
  'The bar filled. The sound played. It was extremely satisfying.',
  'You had one job. You did the one job. System working as designed.',
  'Undo is available and you will not need it.',
  'Filed under: handled.',
  'That one had been on the list long enough to pay rent. Evicted.',
  'The to-do became a did. Grammar has been served.',
  'One less open loop. Your brain just got some RAM back.',
  'Cleared without a guide. No walkthrough. Raw talent.',
  'The pile blinked first.',
] as const;

/** Lines for finishing (or surviving) a timebox. */
/** Lines for finishing a daily ritual — warm, never smug; the day is tended. */
export const RITUAL_LINES: readonly string[] = [
  'Daily thing: done. The day has a spine now.',
  'Same time tomorrow? It’s a date.',
  'Rituals are just self-care with a schedule. Nailed it.',
  'The window was open and you walked through it.',
  'Tiny hinge, big door. That’s a ritual.',
  'Done today. Tomorrow it simply begins again — no debts here.',
  'You kept the small promise. Those are the load-bearing ones.',
  'The routine holds. Civilizations have been built on less.',
  'The candle is lit again. Same flame, new day.',
  'Quietly heroic, daily edition.',
  'Not glamorous. Just kept. That’s the whole magic.',
  'The day and you shook hands on schedule.',
  'One more bead on a very long string.',
  'Kept promises compound. Interest rate: excellent.',
] as const;

export const TIMEBOX_LINES: readonly string[] = [
  'Time. Pencils down. 📝',
  'BRRRING. That’s the round.',
  'The timer has spoken. You may now stretch.',
  'Ding! Your table is ready — table for one, at the couch.',
  '⏰ Deploy complete. Rolling back to rest state.',
  'That’s a wrap on this scene.',
  'Boss defeated: The Ticking Clock.',
  'You have been timeboxed. How do you feel?',
  'Focus streak ended by natural causes.',
  'The sand has run out. Flip me over anytime.',
  'Pomodoro achieved. Tomato acquired. 🍅',
  'GG. The clock never stood a chance.',
  'Round complete. The bell is very proud.',
  'Whistle blown. Hit the showers, champion.',
  'The hourglass respects you now.',
  'Session archived. Muscles (mental): sore in a good way.',
  'The clock ran its race. You ran yours better.',
  'Buzzer beater! …or at least a buzzer meeter.',
] as const;

/** Lines for declaring a work period. */
export const WORK_PERIOD_LINES: readonly string[] = [
  'Clock in. ⏱ Let’s make it count.',
  'Deep work mode: engaged.',
  'The gauntlet is set. Only what fits gets through.',
  'Focus window open. Distractions, form an orderly queue.',
  'Speedrun timer started. Any%.',
  'Right then. Sleeves: rolled.',
  'The forge is hot.',
  'Timer live. May your coffee stay warm exactly as long as needed.',
  'Heads down. The world can buffer.',
  'Session opened. Scope: locked. Vibes: industrial.',
  'The work period sees all fitting tasks. Choose your fighter.',
  'Countdown running. Be the montage.',
  'Door closed, mind open.',
] as const;

/** Lines for sweeping several tasks at once. */
export const BULK_LINES: readonly string[] = [
  'Multi-kill! 💥',
  'A clean sweep. Very satisfying.',
  'Batch processed. Efficiency: unreasonable.',
  'You just did that in bulk. Costco energy.',
  'Mass deletion of obligations. Gorgeous.',
  'That was a combo, and I saw it.',
  'Ah, the ol’ select-and-obliterate. A classic.',
  'Wholesale progress. Retail is for cowards.',
  'One gesture, many victories. Very economical.',
  'The group select giveth, and the group select taketh a LOT away.',
  'Fleet actions on the todo sea. Admiral energy.',
  'Several birds, one extremely efficient stone.',
  'That column of checkmarks appeared in formation. Beautiful drill work.',
] as const;

/** Lines for finishing something other tasks were waiting on. */
export const UNBLOCK_LINES: readonly string[] = [
  'The path is open. 🗝',
  'You just pulled the load-bearing card out. Everything held.',
  'Dependency resolved. npm would be proud.',
  'Door unlocked. Whatever’s behind it is your problem now.',
  'Critical path: cleared.',
  'That was the keystone. The arch stands.',
  'Blocker eliminated. The queue advances.',
  'You were the bottleneck’s bottleneck. Not anymore.',
  'Merge conflict of the soul: resolved.',
  'Green light. ✅ Traffic may proceed.',
  'Chain reaction authorized. Dominoes, fall in.',
  'The dam is open. Let the work flow.',
  'You cleared the one everyone was politely queueing behind.',
  'Root dependency satisfied. The tree may now grow.',
  'That task was a cork. POP.',
] as const;

/** Rarer streak / heater lines — the app noticing you’re on one. */
export const STREAK_LINES: readonly string[] = [
  '🔥 You’re on fire. (metaphorically. hydrate.)',
  '🔥🔥 HEATER. The dice fear you.',
  'You’ve entered THE ZONE. Please keep arms and legs inside the flow state.',
  'Combo ×3! The announcer is losing their mind.',
  'C-C-C-COMBO BREAKER — is what your streak does to procrastination.',
  'The backlog is scared of you today.',
  'Are you… speedrunning your life? Splits look great.',
  'New personal best pace. The ghost car is way behind.',
  'M-M-M-MONSTER STREAK.',
  'The productivity gods demand nothing. They’re just impressed.',
  'Day after day after day. The flame has opinions about you now. Good ones.',
  'The streak is old enough to have a personality. It chose "relentless."',
  'Chain unbroken. Blacksmiths weep at the craftsmanship.',
  'Your consistency has consistency.',
  'This isn’t a hot streak anymore. This is a climate.',
  'The calendar is just a fan account of your streak at this point.',
] as const;

/** Lines for sweep verdicts — brisk, respectful of the courage to decide. */
export const SWEEP_LINES: readonly string[] = [
  'Verdict rendered. Next case.',
  'The backlog thins. The mind clears.',
  'Decisive. The sweep respects decisive.',
  'Another one sorted. Marie Kondo felt a disturbance.',
  'Judged fairly, filed swiftly.',
  'That task waited YEARS for ten seconds of your attention. Worth it.',
  'Curation is creation’s quiet sibling. Nice work.',
  'Snip. The garden looks better already.',
  'The pile shrinks because someone finally LOOKED at it.',
  'Court is efficient today.',
] as const;

/**
 * Evening voice — warmer, quieter, for the end of the day. Gated by the
 * registry to late hours only; the app should feel like it dims with you.
 */
export const NIGHT_NOTES: readonly string[] = [
  'The day is mostly written now. You showed up for it. That was the hard part.',
  'Whatever didn’t get done today wasn’t abandoned — it’s just scheduled for a version of you that’s slept.',
  'Quiet hours. The list can hold everything overnight so you don’t have to.',
  'You did enough today. Not everything — enough. Those were never the same thing.',
  'Night check-in: streak warm, backlog contained, human presumably horizontal soon?',
  'Tomorrow gets a fresh 4am boundary and a fresh you. Both are renewable resources.',
  'The tasks sleep when you do. It’s in their contract.',
  'End-of-day math: what you finished counts once, what you learned counts twice, what you rested counts tomorrow.',
  'Closing thought: nobody remembers the nights they optimized. Go be somewhere soft.',
  'The dice are tired too. See you in the morning. 🌙',
  'If today was heavy, that’s not failure — that’s load-bearing. Set it down for the night.',
  'Last call from your todo list: hydrate, dim the lights, and let the chaos idle till dawn.',
] as const;

/**
 * Occasional genuinely-useful notes — productivity, social, self-kindness.
 * Sparse by design: advice you didn’t ask for is only charming in small doses.
 */
export const TIPS: readonly string[] = [
  'Two-minute rule: if it takes less than two minutes, the fastest system is no system. Just do it now.',
  'Estimates improve fastest when you check them AFTER. You have a screen for that, as it happens.',
  'A task you keep skipping is usually mis-sized, not unimportant. Split it and watch it move.',
  'Naming a task with a VERB doubles its odds: "dentist" is a noun; "book the dentist" is a plan.',
  'The best time to reply to that message was earlier. The second best time is before the guilt compounds.',
  'If everything is high priority, the priorities are decorative. Someday is a feature, not a failure.',
  'Energy beats time: schedule hard thinking where your good hours actually live, not where the calendar has gaps.',
  'When stuck, lower the bar until you’d feel silly NOT starting. Momentum does the rest.',
  'Compliment people behind their backs. It always makes it back around, improved.',
  'A deadline you tell someone about is worth three you keep to yourself.',
  'Rest is a productivity tool with terrible marketing.',
  'Done today beats perfect someday — perfect is just procrastination in a nicer outfit.',
  'Your future self is a coworker. Leave them notes, not mysteries.',
  'The inbox is other people’s priorities. The list is yours. Visit the list first.',
] as const;

/**
 * Lines for adding a task to the day queue — the act of PLANNING, not
 * finishing. The voice notices you rigging tomorrow's dice on purpose.
 */
export const QUEUE_LINES: readonly string[] = [
  'Queued. The dice now owe you a favor.',
  'Stacking the deck, I see. Chaos approves of responsible cheating.',
  'Added to the plan. Tomorrow-you just exhaled.',
  'Onto the conveyor belt it goes.',
  'A plan! An actual plan. The randomizer will pretend not to be moved.',
  'Reservation confirmed. Party of one (task).',
  'The lineup card is set, coach.',
  'Scheduled chaos is still chaos. It’s just polite about it.',
  'The queue accepts your offering.',
  'Noted, numbered, and next-ish.',
  'Front of the line? Not yet. But it’s in the building.',
  'Deck stacked. The deal comes whenever you press the button.',
  'Ah, premeditated productivity. The best kind.',
] as const;

/**
 * Lines for ticking a checklist box inside a todo — a step, not a finish.
 * Kept modest on purpose: the big cheer stays reserved for the whole task.
 */
export const CHECKLIST_LINES: readonly string[] = [
  'One box down. The tiny victories are load-bearing.',
  'Sub-task subdued.',
  'Checked. The list within the list approves.',
  'That’s one fewer thing INSIDE the thing.',
  'Item secured. Inventory updated.',
  'The fine print is getting finished. Bold move.',
  'Line item: lined out.',
  'Piece by piece, the shape appears.',
  'Chipping away. Sculpting, technically.',
  'Small box. Satisfying click.',
  'Every big task is little boxes in a trench coat. Got one.',
  'Progress bar: visibly less bar.',
] as const;
