/** SPOILER ZONE — trivia bank. Ben: close this file. */
import type { TriviaQ } from '../engine';

export const TRIVIA: readonly TriviaQ[] = [
  { q: 'Which planet has the most moons (as of the 2020s count)?', choices: ['Jupiter', 'Saturn', 'Neptune'], answer: 1, reveal: 'Saturn blew past Jupiter — 140+ confirmed moons.' },
  { q: 'What does "HTTP" stand for?', choices: ['HyperText Transfer Protocol', 'High Throughput Transfer Process', 'Hyperlink Text Type Protocol'], answer: 0 },
  { q: 'Name that Pokémon: it evolves from a Magikarp.', choices: ['Gyarados', 'Dratini', 'Feebas'], answer: 0, reveal: 'The ultimate glow-up.' },
  { q: 'Which game popularized "the cake is a lie"?', choices: ['Half-Life 2', 'Portal', 'BioShock'], answer: 1 },
  { q: 'A group of crows is called a…', choices: ['Murder', 'Conspiracy', 'Both, actually'], answer: 2, reveal: 'Murder is common; conspiracy is also attested. Crows contain multitudes.' },
  { q: 'What year did the first Legend of Zelda release in Japan?', choices: ['1984', '1986', '1989'], answer: 1 },
  { q: 'The Konami Code starts with…', choices: ['↑↑↓↓', '←→←→', '↓↓↑↑'], answer: 0 },
  { q: 'How many hearts does an octopus have?', choices: ['1', '3', '9'], answer: 1, reveal: 'Three hearts, nine brains, zero bones. Build of the century.' },
  { q: 'Which of these is NOT a real programming language?', choices: ['Brainfuck', 'LOLCODE', 'HyperScript++'], answer: 2 },
  { q: 'Mario’s original name in Donkey Kong (1981)?', choices: ['Jumpman', 'Mr. Video', 'Plumber Man'], answer: 0 },
  { q: 'What’s the speed of light, roughly?', choices: ['300,000 km/s', '30,000 km/s', '3 million km/s'], answer: 0 },
  { q: 'Digimon: what does Agumon digivolve into (classic)?', choices: ['Greymon', 'Garurumon', 'Angemon'], answer: 0 },
  { q: 'Which anime features the "over 9000" line?', choices: ['Naruto', 'Dragon Ball Z', 'One Piece'], answer: 1 },
  { q: 'The Guinness record for most T-shirts worn at once is about…', choices: ['160', '260', '60'], answer: 1, reveal: 'Ted Hastings wore 260 in 2019. A hero.' },
  { q: 'What does the "M" in MP3 stand for?', choices: ['Music', 'Moving (Picture Experts Group)', 'Media'], answer: 1 },
  { q: 'Which came first?', choices: ['Sliced bread', 'The Nintendo playing-card company', 'The zipper'], answer: 1, reveal: 'Nintendo: 1889. Zipper: 1913. Sliced bread: 1928.' },
  { q: 'How long is a jiffy (computing)?', choices: ['1 ms', '~10 ms (one tick)', '1 µs'], answer: 1 },
  { q: 'The Matrix (1999): which pill does Neo take?', choices: ['Red', 'Blue', 'He refuses both'], answer: 0 },
  { q: 'What animal is Sonic’s friend Knuckles?', choices: ['Armadillo', 'Echidna', 'Hedgehog'], answer: 1 },
  { q: 'Which element has the symbol W?', choices: ['Tungsten', 'Wolframium', 'Both — same element'], answer: 2, reveal: 'W is from "wolfram" — English kept "tungsten."' },
  { q: 'Fastest land animal over short distance?', choices: ['Pronghorn', 'Cheetah', 'Greyhound'], answer: 1 },
  { q: 'In Minecraft, creepers were originally a failed model of a…', choices: ['Pig', 'Cow', 'Zombie'], answer: 0 },
  { q: 'What does "www" have more syllables than?', choices: ['"World Wide Web"', 'It doesn’t', 'Only in French'], answer: 0, reveal: '"Double-u double-u double-u" = 9 syllables. The abbreviation is longer to say.' },
  { q: 'Which planet could float in water (density-wise)?', choices: ['Mars', 'Saturn', 'Mercury'], answer: 1 },
  { q: 'The first video game Easter egg (hidden credit) appeared in…', choices: ['Adventure (Atari 2600)', 'Pac-Man', 'Space Invaders'], answer: 0, reveal: 'Warren Robinett hid his name in 1980 — the term "Easter egg" followed.' },
  { q: 'How many bones does a shark have?', choices: ['0', '~200', '~50'], answer: 0, reveal: 'All cartilage. Sharks are 400-million-year-old flex tape.' },
  { q: 'Which is the ONLY US state without a rectangle-ish flag? (trick!)', choices: ['Ohio', 'Colorado', 'Texas'], answer: 0, reveal: 'Ohio’s flag is a swallowtail pennant.' },
  { q: 'What’s Luigi’s signature year? (Nintendo declared it)', choices: ['2013', '1999', '2020'], answer: 0, reveal: 'The Year of Luigi. We were all there.' },
  { q: 'A "baker’s dozen" is 13 because medieval bakers…', choices: ['Feared shortchanging fines', 'Loved prime numbers', 'Counted in base 13'], answer: 0 },
  { q: 'Which studio made Spirited Away?', choices: ['Studio Ghibli', 'Kyoto Animation', 'Trigger'], answer: 0 },
  { q: 'The average human blinks about how many times a day?', choices: ['1,200', '15,000–20,000', '150,000'], answer: 1 },
  { q: 'GLaDOS runs on which fictional OS?', choices: ['Aperture Science OS', 'GLaDOS is the OS', 'BlackMesaDOS'], answer: 1 },
  { q: 'What color is a polar bear’s skin?', choices: ['Pink', 'Black', 'White'], answer: 1 },
  { q: 'Which key traditionally means "help" in classic apps?', choices: ['F1', 'F5', 'Esc'], answer: 0 },
  { q: 'The longest Monopoly game on record lasted…', choices: ['70 days', '70 hours', 'Both records exist'], answer: 0, reveal: '70 straight days. Straight to jail, honestly.' },
  { q: 'Which of these Zelda items opens most of your problems?', choices: ['Hookshot', 'Bombs', 'The power of friendship'], answer: 1 },
  { q: 'CSS: which is the "holy grail" layout tool of the 2020s?', choices: ['float', 'grid', 'table'], answer: 1 },
  { q: 'Kirby’s home planet?', choices: ['Popstar', 'Dream Land (a country there)', 'Both are accepted'], answer: 2 },
  { q: 'Which came first: sliced bread or the chocolate chip cookie?', choices: ['Sliced bread', 'The cookie', 'Same year'], answer: 0, reveal: 'Bread 1928, cookie 1938. The cookie is younger than sliced bread.' },
  { q: 'Which planet spins backwards (retrograde)?', choices: ['Mars', 'Venus', 'Neptune'], answer: 1 },
  { q: 'The Konami code ends with which two letters?', choices: ['A B', 'B A', 'Select Start'], answer: 1 },
  { q: 'Which animal can sleep for three years straight?', choices: ['A snail', 'A bear', 'A tardigrade'], answer: 0 },
  { q: 'Tetris pieces are called…', choices: ['Tetrominoes', 'Quadblocks', 'Tetragons'], answer: 0 },
  { q: 'What percentage of the ocean is unexplored, roughly?', choices: ['30%', '80%', '99%'], answer: 1 },
  { q: 'Portal’s cake claim: the cake is a…', choices: ['Lie', 'Pie', 'Metaphor and also real, in the ending'], answer: 0 },

  { q: 'Which of these is a real cloud type?', choices: ['Cumulonimbus incus', 'Stratocirrus major', 'Nimbovortex'], answer: 0, reveal: 'The "anvil cloud" — a thunderstorm wearing a hat.' },
  { q: 'In chess, the fewest moves to checkmate is…', choices: ['2', '3', '4'], answer: 0, reveal: "Fool's Mate. It requires a very cooperative opponent." },
  { q: 'What was Google originally called?', choices: ['BackRub', 'SearchIt', 'PageWeb'], answer: 0 },
  { q: 'Hollow Knight: what currency do you collect?', choices: ['Geo', 'Souls', 'Cogs'], answer: 0 },
  { q: 'The Stardew Valley developer team was…', choices: ['One person', '12 people', 'A Nintendo studio'], answer: 0, reveal: 'ConcernedApe, four and a half years, everything solo.' },
  { q: 'Which metal is liquid at room temperature?', choices: ['Mercury', 'Sodium', 'Tin'], answer: 0 },
  { q: 'A group of pugs is called a…', choices: ['Grumble', 'Snort', 'Wrinkle'], answer: 0, reveal: 'A grumble of pugs. Language occasionally gets it exactly right.' },
  { q: 'What does "ELI5" mean online?', choices: ['Explain Like I’m 5', 'Everyone Likes It, 5 stars', 'Early Login In 5'], answer: 0 },
  { q: 'The Sims characters speak…', choices: ['Simlish', 'Esperanto', 'Reversed Dutch'], answer: 0 },
  { q: 'Which organ can regenerate up to ~90% of itself?', choices: ['Liver', 'Kidney', 'Lung'], answer: 0 },
  { q: 'Breath of the Wild: how do you make a fire go out?', choices: ['Rain, mostly', 'Stasis', 'You can’t'], answer: 0 },
  { q: 'The world’s deepest lake is…', choices: ['Baikal', 'Superior', 'Tanganyika'], answer: 0, reveal: 'Baikal — 1,642m deep, one fifth of Earth’s fresh surface water.' },
  { q: 'What does a "farrier" work with?', choices: ['Horseshoes', 'Ferrets', 'Iron ships'], answer: 0 },
  { q: 'Undertale’s most famous mercy option is to…', choices: ['Spare', 'Flee', 'Hug'], answer: 0 },
  { q: 'How fast do your sneezes travel, roughly?', choices: ['~160 km/h', '~30 km/h', '~500 km/h'], answer: 0 },
  { q: 'Which company started as a rice cooker maker?', choices: ['Sony', 'Toyota', 'Samsung'], answer: 0, reveal: 'Sony’s first product flopped — the rice was consistently burnt.' },
  { q: 'A "smoot" is a real unit used to measure…', choices: ['A bridge at MIT', 'Whiskey barrels', 'Cloud height'], answer: 0, reveal: 'The Harvard Bridge: 364.4 smoots plus one ear.' },
  { q: 'Which Ghibli film features a castle that walks?', choices: ["Howl's Moving Castle", 'Castle in the Sky', 'Porco Rosso'], answer: 0 },
  { q: 'Master Chief’s Spartan number?', choices: ['117', '343', '76'], answer: 0 },
  { q: 'Pac-Man was originally named…', choices: ['Puck-Man', 'Chomp-Man', 'Waka-Waka'], answer: 0, reveal: 'Renamed for the West to discourage a certain vandalism.' },
  { q: 'How many Pokémon were in the original Gen 1?', choices: ['150', '151', '155'], answer: 1, reveal: 'Mew, the eternal asterisk.' },
  { q: 'DOOM (the original) released in…', choices: ['1993', '1996', '1990'], answer: 0 },
  { q: 'In Animal Crossing, Tom Nook is a…', choices: ['Tanuki', 'Raccoon', 'Depends on the region, canonically tanuki'], answer: 2 },
  { q: 'Final Fantasy got its name partly because…', choices: ['It was meant to be the studio’s last shot', 'The hero’s name was Fantasy', 'A translation error'], answer: 0, reveal: 'Square was struggling; the "final" gamble spawned 16+ sequels.' },
  { q: 'Skyrim guards famously took an arrow to the…', choices: ['Knee', 'Shoulder', 'Shield'], answer: 0 },
  { q: 'Metroid’s big 1986 reveal was that Samus…', choices: ['Is a woman', 'Is a robot', 'Is the villain'], answer: 0 },
  { q: 'Half-Life’s iconic melee weapon?', choices: ['Crowbar', 'Wrench', 'Stun baton'], answer: 0 },
  { q: 'Mario Kart’s most feared item?', choices: ['Blue shell', 'Red shell', 'Banana'], answer: 0, reveal: 'It punishes success. A morality tale at 200cc.' },
  { q: 'Among Us popularized which word?', choices: ['Sus', 'Poggers', 'Yeet'], answer: 0 },
  { q: 'Hades (the game) has you escaping as…', choices: ['Zagreus', 'Theseus', 'Achilles'], answer: 0 },
  { q: 'Celeste is about climbing a mountain and…', choices: ['Anxiety', 'A dragon', 'Time travel'], answer: 0, reveal: 'The best platformer ever made about being kind to yourself.' },
  { q: 'Ocarina of Time’s infamous companion catchphrase?', choices: ['"Hey! Listen!"', '"Watch out!"', '"Over here!"'], answer: 0 },

  { q: '"Finish the Fight" was the tagline of…', choices: ['Halo 2', 'Halo 3', 'Halo: Reach'], answer: 1 },
  { q: 'Minecraft’s original soundtrack was composed by…', choices: ['Koji Kondo', 'C418', 'Mick Gordon'], answer: 1, reveal: 'Daniel Rosenfeld — the calmest music ever written for a game about punching trees.' },
  { q: 'Which game’s speedruns made the "backwards long jump" famous?', choices: ['Sonic Adventure', 'Crash Bandicoot', 'Super Mario 64'], answer: 2 },
  { q: 'EarthBound’s hero is named…', choices: ['Lucas', 'Ness', 'Ninten'], answer: 1 },
  { q: 'Before Rocket League, Psyonix made…', choices: ['Supersonic Acrobatic Rocket-Powered Battle-Cars', 'Hot Wheels Unleashed', 'Twisted Metal'], answer: 0, reveal: 'Same game, catchier name the second time.' },
  { q: 'The best-selling video game of all time?', choices: ['Tetris', 'Minecraft', 'GTA V'], answer: 1, reveal: '300M+ copies — though Tetris’s 40-year count is famously murky.' },
  { q: 'Portal 2’s Wheatley is voiced by…', choices: ['Stephen Merchant', 'Simon Pegg', 'Martin Freeman'], answer: 0 },
  { q: 'Which console made the analog stick standard?', choices: ['PlayStation', 'Nintendo 64', 'Dreamcast'], answer: 1, reveal: 'Mid-generation, Sony answered with the DualShock — and kept the name.' },
  { q: 'Cuphead’s art style imitates cartoons of the…', choices: ['1930s', '1950s', '1970s'], answer: 0, reveal: 'Hand-drawn cels, period jazz, and period-accurate unfairness.' },
  { q: 'In speedrunning, "TAS" stands for…', choices: ['Timed Attack Session', 'Tool-Assisted Speedrun', 'True Any% Standard'], answer: 1 },
  { q: 'Chrono Trigger’s "Dream Team" included the creator of…', choices: ['Dragon Ball', 'One Piece', 'Sailor Moon'], answer: 0, reveal: 'Akira Toriyama on art, with Dragon Quest’s Horii and Final Fantasy’s Sakaguchi.' },
  { q: 'The PS1’s famously wobbly textures come from…', choices: ['CRT ghosting', 'Compression artifacts', 'No sub-pixel vertex precision'], answer: 2, reveal: 'Integer snapping — the jitter is the console’s soul.' },
  { q: 'Properly stored honey lasts…', choices: ['~10 years', '~50 years', 'Basically forever'], answer: 2, reveal: 'Edible honey has been found in 3,000-year-old Egyptian tombs.' },
  { q: 'Bananas are botanically…', choices: ['Berries', 'Drupes', 'Nuts'], answer: 0, reveal: 'And strawberries aren’t berries. Botany runs on chaos.' },

  { q: 'In Katamari Damacy, you roll up the world to rebuild…', choices: ['A city', 'The stars', 'A garden'], answer: 1, reveal: 'The King of All Cosmos broke them. You clean up. Classic parenting.' },
  { q: 'Journey (2012) lets you meet other players and communicate only by…', choices: ['Text chat', 'Emotes menu', 'A wordless chirp'], answer: 2 },
  { q: 'Which studio made Dark Souls?', choices: ['Platinum', 'FromSoftware', 'Atlus'], answer: 1 },
  { q: 'Slay the Spire popularised which genre mashup?', choices: ['Deckbuilding roguelike', 'Farming shooter', 'Rhythm RPG'], answer: 0 },
  { q: 'Splatoon’s multiplayer scores you on…', choices: ['Kills', 'Ground covered in ink', 'Time held'], answer: 1 },
  { q: 'The first message sent over ARPANET was meant to be "LOGIN". It got as far as…', choices: ['"LO"', '"LOG"', '"L"'], answer: 0, reveal: 'The system crashed after two letters. A humble "lo" started the internet.' },
  { q: 'Why is QWERTY laid out that way?', choices: ['Fastest possible typing', 'To separate common letter pairs', 'Alphabetical leftovers'], answer: 1 },
  { q: 'Ada Lovelace is credited with writing the first…', choices: ['Compiler', 'Computer program', 'Operating system'], answer: 1, reveal: 'For a machine that was never built. Ahead of her time, literally.' },
  { q: 'An axolotl can regrow…', choices: ['Limbs only', 'Limbs and organs', 'Limbs, organs, and parts of its brain'], answer: 2 },
  { q: 'The "404" error number refers to…', choices: ['A room at CERN', 'Just a status code, no room', 'The 404th HTTP draft'], answer: 1, reveal: 'The room-404 story is a great myth. The code is simply 4xx = your side, 04 = not found.' },
] as const;
