/** SPOILER ZONE — trivia bank. Ben: close this file. */
import type { TriviaQ } from '../engine';

export const TRIVIA: readonly TriviaQ[] = [
  { q: 'Which planet has the most moons (as of the 2020s count)?', choices: ['Jupiter', 'Saturn', 'Neptune'], answer: 1, reveal: 'Saturn blew past Jupiter — 140+ confirmed moons.' },
  { q: 'What does "HTTP" stand for?', choices: ['HyperText Transfer Protocol', 'High Throughput Transfer Process', 'Hyperlink Text Type Protocol'], answer: 0 },
  { q: 'Name that Pokémon: it evolves from a Magikarp.', choices: ['Gyarados', 'Dratini', 'Feebas'], answer: 0, reveal: 'The ultimate glow-up.' },
  { q: 'Which game popularized "the cake is a lie"?', choices: ['Half-Life 2', 'Portal', 'BioShock'], answer: 1 },
  { q: 'A group of crows is called a…', choices: ['Murder', 'Conspiracy', 'Both, actually'], answer: 2, reveal: 'Murder is common; conspiracy is also attested. Crows contain multitudes.' },
  { q: 'What year did the first Legend of Zelda release in Japan?', choices: ['1984', '1986', '1989'], answer: 1 },
  { q: 'The Konami Code starts with…', choices: ['↑↑↓↓', '←→←→', '↓↓↑↑'], answer: 0 },
  { q: 'How many hearts does an octopus have?', choices: ['1', '3', '9'], answer: 1, reveal: 'Three hearts, nine brains, zero bones. Build of the century.' },
  { q: 'Which of these is NOT a real programming language?', choices: ['Brainfuck', 'LOLCODE', 'HyperScript++'], answer: 2 },
  { q: 'Mario’s original name in Donkey Kong (1981)?', choices: ['Jumpman', 'Mr. Video', 'Plumber Man'], answer: 0 },
  { q: 'What’s the speed of light, roughly?', choices: ['300,000 km/s', '30,000 km/s', '3 million km/s'], answer: 0 },
  { q: 'Digimon: what does Agumon digivolve into (classic)?', choices: ['Greymon', 'Garurumon', 'Angemon'], answer: 0 },
  { q: 'Which anime features the "over 9000" line?', choices: ['Naruto', 'Dragon Ball Z', 'One Piece'], answer: 1 },
  { q: 'The Guinness record for most T-shirts worn at once is about…', choices: ['160', '260', '60'], answer: 1, reveal: 'Ted Hastings wore 260 in 2019. A hero.' },
  { q: 'What does the "M" in MP3 stand for?', choices: ['Music', 'Moving (Picture Experts Group)', 'Media'], answer: 1 },
  { q: 'Which came first?', choices: ['Sliced bread', 'The Nintendo playing-card company', 'The zipper'], answer: 1, reveal: 'Nintendo: 1889. Zipper: 1913. Sliced bread: 1928.' },
  { q: 'How long is a jiffy (computing)?', choices: ['1 ms', '~10 ms (one tick)', '1 µs'], answer: 1 },
  { q: 'The Matrix (1999): which pill does Neo take?', choices: ['Red', 'Blue', 'He refuses both'], answer: 0 },
  { q: 'What animal is Sonic’s friend Knuckles?', choices: ['Armadillo', 'Echidna', 'Hedgehog'], answer: 1 },
  { q: 'Which element has the symbol W?', choices: ['Tungsten', 'Wolframium', 'Both — same element'], answer: 2, reveal: 'W is from "wolfram" — English kept "tungsten."' },
  { q: 'Fastest land animal over short distance?', choices: ['Pronghorn', 'Cheetah', 'Greyhound'], answer: 1 },
  { q: 'In Minecraft, creepers were originally a failed model of a…', choices: ['Pig', 'Cow', 'Zombie'], answer: 0 },
  { q: 'What does "www" have more syllables than?', choices: ['"World Wide Web"', 'It doesn’t', 'Only in French'], answer: 0, reveal: '"Double-u double-u double-u" = 9 syllables. The abbreviation is longer to say.' },
  { q: 'Which planet could float in water (density-wise)?', choices: ['Mars', 'Saturn', 'Mercury'], answer: 1 },
  { q: 'The first video game Easter egg (hidden credit) appeared in…', choices: ['Adventure (Atari 2600)', 'Pac-Man', 'Space Invaders'], answer: 0, reveal: 'Warren Robinett hid his name in 1980 — the term "Easter egg" followed.' },
  { q: 'How many bones does a shark have?', choices: ['0', '~200', '~50'], answer: 0, reveal: 'All cartilage. Sharks are 400-million-year-old flex tape.' },
  { q: 'Which is the ONLY US state without a rectangle-ish flag? (trick!)', choices: ['Ohio', 'Colorado', 'Texas'], answer: 0, reveal: 'Ohio’s flag is a swallowtail pennant.' },
  { q: 'What’s Luigi’s signature year? (Nintendo declared it)', choices: ['2013', '1999', '2020'], answer: 0, reveal: 'The Year of Luigi. We were all there.' },
  { q: 'A "baker’s dozen" is 13 because medieval bakers…', choices: ['Feared shortchanging fines', 'Loved prime numbers', 'Counted in base 13'], answer: 0 },
  { q: 'Which studio made Spirited Away?', choices: ['Studio Ghibli', 'Kyoto Animation', 'Trigger'], answer: 0 },
  { q: 'The average human blinks about how many times a day?', choices: ['1,200', '15,000–20,000', '150,000'], answer: 1 },
  { q: 'GLaDOS runs on which fictional OS?', choices: ['Aperture Science OS', 'GLaDOS is the OS', 'BlackMesaDOS'], answer: 1 },
  { q: 'What color is a polar bear’s skin?', choices: ['Pink', 'Black', 'White'], answer: 1 },
  { q: 'Which key traditionally means "help" in classic apps?', choices: ['F1', 'F5', 'Esc'], answer: 0 },
  { q: 'The longest Monopoly game on record lasted…', choices: ['70 days', '70 hours', 'Both records exist'], answer: 0, reveal: '70 straight days. Straight to jail, honestly.' },
  { q: 'Which of these Zelda items opens most of your problems?', choices: ['Hookshot', 'Bombs', 'The power of friendship'], answer: 1 },
  { q: 'CSS: which is the "holy grail" layout tool of the 2020s?', choices: ['float', 'grid', 'table'], answer: 1 },
  { q: 'Kirby’s home planet?', choices: ['Popstar', 'Dream Land (a country there)', 'Both are accepted'], answer: 2 },
] as const;
